[workspace]
members = ["node", "runtime", "template-fuzzer"]
resolver = "2"

[workspace.package]
authors = ["Xcavate"]
description = "Xcavate Parachain"
edition = "2021"
license = "GPL-3.0-only"
repository = "https://github.com/XcavateBlockchain/xcavate-node-paseo"
homepage = "https://xcavate.io/"

[workspace.dependencies]
clap = { version = "4.5.3", features = ["derive"] }
color-print = "0.3.4"
futures = "0.3.28"
hex-literal = "0.4.1"
jsonrpsee = { version = "0.22", features = ["server"] }
log = { version = "0.4.20", default-features = false }
parity-scale-codec = { version = "3.0.0", default-features = false, features = [
	"derive",
	"max-encoded-len",
] }
scale-info = { version = "2.10.0", default-features = false }
serde = { version = "1.0.188", default-features = false }
serde_json = "1.0.108"
smallvec = "1.11.0"

# Substrate
frame-benchmarking = { version = "33.0.0", default-features = false }
frame-benchmarking-cli = { version = "37.0.0", default-features = false }
frame-executive = { version = "33.0.1", default-features = false }
frame-support = { version = "33.0.0", default-features = false }
frame-system = { version = "33.0.0", default-features = false }
frame-system-benchmarking = { version = "33.0.0", default-features = false }
frame-system-rpc-runtime-api = { version = "31.0.0", default-features = false }
frame-try-runtime = { version = "0.39.0", default-features = false }
pallet-assets = { version = "34.0.0", default-features = false }
pallet-aura = { version = "32.0.0", default-features = false }
pallet-authorship = { version = "33.0.0", default-features = false }
pallet-balances = { version = "34.0.0", default-features = false }
pallet-message-queue = { version = "36.0.0", default-features = false }
pallet-multisig = { version = "33.0.0", default-features = false }
pallet-proxy = { version = "33.0.0", default-features = false }
pallet-session = { version = "33.0.0", default-features = false }
pallet-sudo = { version = "33.0.0", default-features = false }
pallet-timestamp = { version = "32.0.0", default-features = false }
pallet-transaction-payment = { version = "33.0.0", default-features = false }
pallet-transaction-payment-rpc = { version = "35.0.0", default-features = false }
pallet-transaction-payment-rpc-runtime-api = { version = "33.0.0", default-features = false }
pallet-utility = { version = "33.0.0", default-features = false }
sc-basic-authorship = { version = "0.39.0", default-features = false }
sc-chain-spec = { version = "32.0.0", default-features = false }
sc-cli = { version = "0.41.0", default-features = false }
sc-client-api = { version = "33.0.0", default-features = false }
sc-consensus = { version = "0.38.0", default-features = false }
sc-executor = { version = "0.37.0", default-features = false }
sc-network = { version = "0.39.0", default-features = false }
sc-network-sync = { version = "0.38.0", default-features = false }
sc-offchain = { version = "34.0.0", default-features = false }
sc-rpc = { version = "34.0.0", default-features = false }
sc-service = { version = "0.40.0", default-features = false }
sc-sysinfo = { version = "32.0.0", default-features = false }
sc-telemetry = { version = "19.0.0", default-features = false }
sc-tracing = { version = "33.0.0", default-features = false }
sc-transaction-pool = { version = "33.0.0", default-features = false }
sc-transaction-pool-api = { version = "33.0.0", default-features = false }
sp-api = { version = "31.0.0", default-features = false }
sp-arithmetic = { version = "26.0.0", default-features = false }
sp-block-builder = { version = "31.0.0", default-features = false }
sp-blockchain = { version = "33.0.0", default-features = false }
sp-consensus-aura = { version = "0.37.0", default-features = false }
sp-core = { version = "32.0.0", default-features = false }
sp-genesis-builder = { version = "0.12.0", default-features = false }
sp-inherents = { version = "31.0.0", default-features = false }
sp-io = { version = "35.0.0" }
sp-keystore = { version = "0.38.0", default-features = false }
sp-offchain = { version = "31.0.0", default-features = false }
sp-runtime = { version = "36.0.0", default-features = false }
sp-session = { version = "32.0.0", default-features = false }
sp-state-machine = { version = "0.40.0", default-features = false }
sp-std = { version = "14.0.0", default-features = false }
sp-timestamp = { version = "31.0.0", default-features = false }
sp-transaction-pool = { version = "31.0.0", default-features = false }
sp-version = { version = "34.0.0", default-features = false }
substrate-build-script-utils = { version = "11.0.0" }
substrate-frame-rpc-system = { version = "33.0.0", default-features = false }
substrate-prometheus-endpoint = { version = "0.17.0", default-features = false }
substrate-wasm-builder = { version = "22.0.1" }

# Polkadot
pallet-xcm = { version = "12.0.0", default-features = false }
polkadot-cli = { version = "12.0.0" }
polkadot-parachain-primitives = { version = "11.0.0", default-features = false }
polkadot-primitives = { version = "12.0.0", default-features = false }
polkadot-runtime-common = { version = "12.0.0", default-features = false }
xcm = { version = "12.0.0", package = "staging-xcm", default-features = false }
xcm-builder = { version = "12.0.0", package = "staging-xcm-builder", default-features = false }
xcm-executor = { version = "12.0.0", package = "staging-xcm-executor", default-features = false }

# Cumulus
assets-common = { version = "0.12.0", default-features = false }
cumulus-client-cli = { version = "0.12.0", default-features = false }
cumulus-client-collator = { version = "0.12.0", default-features = false }
cumulus-client-consensus-aura = { version = "0.12.0", default-features = false }
cumulus-client-consensus-common = { version = "0.12.0", default-features = false }
cumulus-client-consensus-proposer = { version = "0.12.0", default-features = false }
cumulus-client-service = { version = "0.12.0", default-features = false }
cumulus-pallet-aura-ext = { version = "0.12.0", default-features = false }
cumulus-pallet-parachain-system = { version = "0.12.0", default-features = false }
cumulus-pallet-session-benchmarking = { version = "14.0.0", default-features = false }
cumulus-pallet-xcm = { version = "0.12.0", default-features = false }
cumulus-pallet-xcmp-queue = { version = "0.12.0", default-features = false }
cumulus-primitives-aura = { version = "0.12.0", default-features = false }
cumulus-primitives-core = { version = "0.12.0", default-features = false }
cumulus-primitives-parachain-inherent = { version = "0.12.0", default-features = false }
cumulus-primitives-storage-weight-reclaim = { version = "3.0.0", default-features = false }
cumulus-primitives-utility = { version = "0.12.0", default-features = false }
cumulus-relay-chain-interface = { version = "0.12.0", default-features = false }
cumulus-test-relay-sproof-builder = { version = "0.12.0", default-features = false }
pallet-collator-selection = { version = "14.0.0", default-features = false }
parachain-info = { version = "0.12.0", package = "staging-parachain-info", default-features = false }
parachains-common = { version = "12.0.0", default-features = false }

# Fuzzer
substrate-runtime-fuzzer = { git = "https://github.com/srlabs/substrate-runtime-fuzzer.git", default-features = false }
ziggy = { version = "0.8", default-features = false }


[workspace.lints.clippy]
large_enum_variant = "allow"
too_many_arguments = "allow"
type_complexity = "allow"

[profile.production]
codegen-units = 1
inherits = "release"
lto = true


[profile.release]
opt-level = 3
panic = "unwind"
