[workspace]
members = ["node", "runtime"]
exclude = ["integration-tests"]
resolver = "2"

[workspace.package]
authors = ["Xcavate"]
description = "Xcavate Parachain"
edition = "2021"
license = "GPL-3.0-only"
repository = "https://github.com/XcavateBlockchain/xcavate-node-paseo"
homepage = "https://xcavate.io/"
version = "1.0.0"

[workspace.dependencies]
base58 = { version = "0.2.0", default-features = false }
bitflags = { version = "1.3.2", default-features = false }
clap = { version = "4.5.3", features = ["derive"] }
color-print = "0.3.4"
env_logger = { version = "0.10.0" }
fluent-uri = { version = "0.1.4", default-features = false }
futures = "0.3.31"
hex = { version = "0.4.0", default-features = false }
hex-literal = "0.4.1"
jsonrpsee = { version = "0.24.7", features = ["server"] }
libsecp256k1 = { version = "0.7", default-features = false }
log = { version = "0.4.22", default-features = false }
parity-scale-codec = { version = "3.7.5", default-features = false, features = [
	"derive",
	"max-encoded-len",
] }
scale-info = { version = "2.11.6", default-features = false }
serde = { version = "1.0.214", default-features = false }
serde_json = "1.0.132"
sha3 = { version = "0.10.0", default-features = false }
smallvec = "1.13.2"

# Substrate
frame-benchmarking = { git = "https://github.com/paritytech/polkadot-sdk", default-features = false, branch = "stable2503" }
frame-benchmarking-cli = { git = "https://github.com/paritytech/polkadot-sdk", default-features = false, branch = "stable2503" }
frame-executive = { git = "https://github.com/paritytech/polkadot-sdk", default-features = false, branch = "stable2503" }
frame-support = { git = "https://github.com/paritytech/polkadot-sdk", default-features = false, branch = "stable2503" }
frame-system = { git = "https://github.com/paritytech/polkadot-sdk", default-features = false, branch = "stable2503" }
frame-system-benchmarking = { git = "https://github.com/paritytech/polkadot-sdk", default-features = false, branch = "stable2503" }
frame-system-rpc-runtime-api = { git = "https://github.com/paritytech/polkadot-sdk", default-features = false, branch = "stable2503" }
frame-try-runtime = { git = "https://github.com/paritytech/polkadot-sdk", default-features = false, branch = "stable2503" }
pallet-assets = { git = "https://github.com/paritytech/polkadot-sdk", default-features = false, branch = "stable2503" }
pallet-aura = { git = "https://github.com/paritytech/polkadot-sdk", default-features = false, branch = "stable2503" }
pallet-authorship = { git = "https://github.com/paritytech/polkadot-sdk", default-features = false, branch = "stable2503" }
pallet-balances = { git = "https://github.com/paritytech/polkadot-sdk", default-features = false, branch = "stable2503" }
pallet-message-queue = { git = "https://github.com/paritytech/polkadot-sdk", default-features = false, branch = "stable2503" }
pallet-multisig = { git = "https://github.com/paritytech/polkadot-sdk", default-features = false, branch = "stable2503" }
pallet-proxy = { git = "https://github.com/paritytech/polkadot-sdk", default-features = false, branch = "stable2503" }
pallet-session = { git = "https://github.com/paritytech/polkadot-sdk", default-features = false, branch = "stable2503" }
pallet-sudo = { git = "https://github.com/paritytech/polkadot-sdk", default-features = false, branch = "stable2503" }
pallet-timestamp = { git = "https://github.com/paritytech/polkadot-sdk", default-features = false, branch = "stable2503" }
pallet-transaction-payment = { git = "https://github.com/paritytech/polkadot-sdk", default-features = false, branch = "stable2503" }
pallet-transaction-payment-rpc = { git = "https://github.com/paritytech/polkadot-sdk", default-features = false, branch = "stable2503" }
pallet-transaction-payment-rpc-runtime-api = { git = "https://github.com/paritytech/polkadot-sdk", default-features = false, branch = "stable2503" }
pallet-utility = { git = "https://github.com/paritytech/polkadot-sdk", default-features = false, branch = "stable2503" }
pallet-nfts = { git = "https://github.com/paritytech/polkadot-sdk", default-features = false, branch = "stable2503" }
pallet-nft-fractionalization = { git = "https://github.com/paritytech/polkadot-sdk", default-features = false, branch = "stable2503" }
pallet-assets-holder = { git = "https://github.com/paritytech/polkadot-sdk", default-features = false, branch = "stable2503" }
pallet-assets-freezer = { git = "https://github.com/paritytech/polkadot-sdk", default-features = false, branch = "stable2503" }
pallet-vesting = { git = "https://github.com/paritytech/polkadot-sdk", default-features = false, branch = "stable2503" }
sc-basic-authorship = { git = "https://github.com/paritytech/polkadot-sdk", default-features = false, branch = "stable2503" }
sc-chain-spec = { git = "https://github.com/paritytech/polkadot-sdk", default-features = false, branch = "stable2503" }
sc-cli = { git = "https://github.com/paritytech/polkadot-sdk", default-features = false, branch = "stable2503" }
sc-client-api = { git = "https://github.com/paritytech/polkadot-sdk", default-features = false, branch = "stable2503" }
sc-consensus = { git = "https://github.com/paritytech/polkadot-sdk", default-features = false, branch = "stable2503" }
sc-executor = { git = "https://github.com/paritytech/polkadot-sdk", default-features = false, branch = "stable2503" }
sc-network = { git = "https://github.com/paritytech/polkadot-sdk", default-features = false, branch = "stable2503" }
sc-network-sync = { git = "https://github.com/paritytech/polkadot-sdk", default-features = false, branch = "stable2503" }
sc-offchain = { git = "https://github.com/paritytech/polkadot-sdk", default-features = false, branch = "stable2503" }
sc-rpc = { git = "https://github.com/paritytech/polkadot-sdk", default-features = false, branch = "stable2503" }
sc-service = { git = "https://github.com/paritytech/polkadot-sdk", default-features = false, branch = "stable2503" }
sc-sysinfo = { git = "https://github.com/paritytech/polkadot-sdk", default-features = false, branch = "stable2503" }
sc-telemetry = { git = "https://github.com/paritytech/polkadot-sdk", default-features = false, branch = "stable2503" }
sc-tracing = { git = "https://github.com/paritytech/polkadot-sdk", default-features = false, branch = "stable2503" }
sc-transaction-pool = { git = "https://github.com/paritytech/polkadot-sdk", default-features = false, branch = "stable2503" }
sc-transaction-pool-api = { git = "https://github.com/paritytech/polkadot-sdk", default-features = false, branch = "stable2503" }
sp-api = { git = "https://github.com/paritytech/polkadot-sdk", default-features = false, branch = "stable2503" }
sp-arithmetic = { git = "https://github.com/paritytech/polkadot-sdk", default-features = false, branch = "stable2503" }
sp-block-builder = { git = "https://github.com/paritytech/polkadot-sdk", default-features = false, branch = "stable2503" }
sp-blockchain = { git = "https://github.com/paritytech/polkadot-sdk", default-features = false, branch = "stable2503" }
sp-consensus-aura = { git = "https://github.com/paritytech/polkadot-sdk", default-features = false, branch = "stable2503" }
sp-core = { git = "https://github.com/paritytech/polkadot-sdk", default-features = false, branch = "stable2503" }
sp-genesis-builder = { git = "https://github.com/paritytech/polkadot-sdk", default-features = false, branch = "stable2503" }
sp-inherents = { git = "https://github.com/paritytech/polkadot-sdk", default-features = false, branch = "stable2503" }
sp-io = { git = "https://github.com/paritytech/polkadot-sdk", default-features = false, branch = "stable2503" }
sp-keystore = { git = "https://github.com/paritytech/polkadot-sdk", default-features = false, branch = "stable2503" }
sp-offchain = { git = "https://github.com/paritytech/polkadot-sdk", default-features = false, branch = "stable2503" }
sp-runtime = { git = "https://github.com/paritytech/polkadot-sdk", default-features = false, branch = "stable2503" }
sp-session = { git = "https://github.com/paritytech/polkadot-sdk", default-features = false, branch = "stable2503" }
sp-state-machine = { git = "https://github.com/paritytech/polkadot-sdk", default-features = false, branch = "stable2503" }
sp-timestamp = { git = "https://github.com/paritytech/polkadot-sdk", default-features = false, branch = "stable2503" }
sp-transaction-pool = { git = "https://github.com/paritytech/polkadot-sdk", default-features = false, branch = "stable2503" }
sp-version = { git = "https://github.com/paritytech/polkadot-sdk", default-features = false, branch = "stable2503" }
sp-std = { git = "https://github.com/paritytech/polkadot-sdk", default-features = false, branch = "stable2503" }
sp-weights = { git = "https://github.com/paritytech/polkadot-sdk", default-features = false, branch = "stable2503" }
substrate-build-script-utils = { git = "https://github.com/paritytech/polkadot-sdk", branch = "stable2503" }
substrate-frame-rpc-system = { git = "https://github.com/paritytech/polkadot-sdk", default-features = false, branch = "stable2503" }
substrate-prometheus-endpoint = { git = "https://github.com/paritytech/polkadot-sdk", default-features = false, branch = "stable2503" }
substrate-wasm-builder = { git = "https://github.com/paritytech/polkadot-sdk", branch = "stable2503" }
frame-metadata-hash-extension = { git = "https://github.com/paritytech/polkadot-sdk", default-features = false, branch = "stable2503" }
sp-keyring = { git = "https://github.com/paritytech/polkadot-sdk", default-features = false, branch = "stable2503" }

# Polkadot
pallet-xcm = { git = "https://github.com/paritytech/polkadot-sdk", default-features = false, branch = "stable2503" }
polkadot-cli = { git = "https://github.com/paritytech/polkadot-sdk", branch = "stable2503" }
polkadot-parachain-primitives = { git = "https://github.com/paritytech/polkadot-sdk", default-features = false, branch = "stable2503" }
polkadot-primitives = { git = "https://github.com/paritytech/polkadot-sdk", default-features = false, branch = "stable2503" }
polkadot-runtime-common = { git = "https://github.com/paritytech/polkadot-sdk", default-features = false, branch = "stable2503" }
xcm = { package = "staging-xcm", git = "https://github.com/paritytech/polkadot-sdk", default-features = false, branch = "stable2503" }
xcm-builder = { package = "staging-xcm-builder", git = "https://github.com/paritytech/polkadot-sdk", default-features = false, branch = "stable2503" }
xcm-executor = { package = "staging-xcm-executor", git = "https://github.com/paritytech/polkadot-sdk", default-features = false, branch = "stable2503" }

# Cumulus
assets-common = { git = "https://github.com/paritytech/polkadot-sdk", default-features = false, branch = "stable2503" }
cumulus-client-cli = { git = "https://github.com/paritytech/polkadot-sdk", default-features = false, branch = "stable2503" }
cumulus-client-collator = { git = "https://github.com/paritytech/polkadot-sdk", default-features = false, branch = "stable2503" }
cumulus-client-consensus-aura = { git = "https://github.com/paritytech/polkadot-sdk", default-features = false, branch = "stable2503" }
cumulus-client-consensus-common = { git = "https://github.com/paritytech/polkadot-sdk", default-features = false, branch = "stable2503" }
cumulus-client-consensus-proposer = { git = "https://github.com/paritytech/polkadot-sdk", default-features = false, branch = "stable2503" }
cumulus-client-service = { git = "https://github.com/paritytech/polkadot-sdk", default-features = false, branch = "stable2503" }
cumulus-pallet-aura-ext = { git = "https://github.com/paritytech/polkadot-sdk", default-features = false, branch = "stable2503" }
cumulus-pallet-parachain-system = { git = "https://github.com/paritytech/polkadot-sdk", default-features = false, branch = "stable2503" }
cumulus-pallet-session-benchmarking = { git = "https://github.com/paritytech/polkadot-sdk", default-features = false, branch = "stable2503" }
cumulus-pallet-xcm = { git = "https://github.com/paritytech/polkadot-sdk", default-features = false, branch = "stable2503" }
cumulus-pallet-xcmp-queue = { git = "https://github.com/paritytech/polkadot-sdk", default-features = false, branch = "stable2503" }
cumulus-primitives-aura = { git = "https://github.com/paritytech/polkadot-sdk", default-features = false, branch = "stable2503" }
cumulus-primitives-core = { git = "https://github.com/paritytech/polkadot-sdk", default-features = false, branch = "stable2503" }
cumulus-primitives-parachain-inherent = { git = "https://github.com/paritytech/polkadot-sdk", default-features = false, branch = "stable2503" }
cumulus-pallet-weight-reclaim = { git = "https://github.com/paritytech/polkadot-sdk", default-features = false, branch = "stable2503" }
cumulus-primitives-utility = { git = "https://github.com/paritytech/polkadot-sdk", default-features = false, branch = "stable2503" }
cumulus-relay-chain-interface = { git = "https://github.com/paritytech/polkadot-sdk", default-features = false, branch = "stable2503" }
cumulus-test-relay-sproof-builder = { git = "https://github.com/paritytech/polkadot-sdk", default-features = false, branch = "stable2503" }
pallet-collator-selection = { git = "https://github.com/paritytech/polkadot-sdk", default-features = false, branch = "stable2503" }
parachain-info = { package = "staging-parachain-info", git = "https://github.com/paritytech/polkadot-sdk", default-features = false, branch = "stable2503" }
parachains-common = { git = "https://github.com/paritytech/polkadot-sdk", default-features = false, branch = "stable2503" }

# ISMP
anyhow = { version = "1.0.98", default-features = false }
ismp = { git = "https://github.com/polytope-labs/hyperbridge", branch = "polkadot-stable2503", default-features = false }
ismp-parachain = { git = "https://github.com/polytope-labs/hyperbridge", branch = "polkadot-stable2503", default-features = false }
ismp-parachain-inherent = { git = "https://github.com/polytope-labs/hyperbridge", branch = "polkadot-stable2503", default-features = false }
ismp-parachain-runtime-api = { git = "https://github.com/polytope-labs/hyperbridge", branch = "polkadot-stable2503", default-features = false }
pallet-hyperbridge = { git = "https://github.com/polytope-labs/hyperbridge", branch = "polkadot-stable2503", default-features = false }
pallet-ismp = { git = "https://github.com/polytope-labs/hyperbridge", branch = "polkadot-stable2503", default-features = false }
pallet-ismp-rpc = { git = "https://github.com/polytope-labs/hyperbridge", branch = "polkadot-stable2503" }
pallet-ismp-runtime-api = { git = "https://github.com/polytope-labs/hyperbridge", branch = "polkadot-stable2503", default-features = false }
pallet-token-gateway = { git = "https://github.com/polytope-labs/hyperbridge", branch = "polkadot-stable2503", default-features = false }

# Local Dependencies
pallet-xcavate-whitelist = {  path = "./pallets/xcavate-whitelist", default-features = false }
pallet-education-regions = {  path = "./pallets/education-regions", default-features = false }
pallet-real-x-education = { path = "./pallets/real-x-education", default-features = false }
pallet-marketplace = { path = "./pallets/marketplace", default-features = false }
pallet-property-management = {  path = "./pallets/property-management", default-features = false }
pallet-property-governance = {  path = "./pallets/property-governance", default-features = false }
pallet-regions = {  path = "./pallets/regions", default-features = false }
pallet-real-world-asset = {  path = "./pallets/real-world-asset", default-features = false }
pallet-bucket = { path = "./pallets/pallet-bucket", default-features = false }

# KILT DIDs
kilt-support = { path = "support", default-features = false }
kilt-asset-dids = { path = "crates/assets", default-features = false }
attestation = { path = "kilt-pallets/attestation", default-features = false }
ctype = { path = "kilt-pallets/ctype", default-features = false }
delegation = { path = "kilt-pallets/delegation", default-features = false }
did = { path = "kilt-pallets/did", default-features = false }
pallet-did-lookup = { path = "kilt-pallets/pallet-did-lookup", default-features = false }
public-credentials = { path = "kilt-pallets/public-credentials", default-features = false }
pallet-kilt-migration = { path = "kilt-pallets/pallet-migration", default-features = false }
kilt-runtime-api-did = { path = "runtime-api/did", default-features = false }
kilt-runtime-api-public-credentials = { path = "runtime-api/public-credentials", default-features = false }

# Fuzzer
#substrate-runtime-fuzzer = { git = "https://github.com/srlabs/substrate-runtime-fuzzer.git", default-features = false }
#ziggy = { version = "0.8", default-features = false }


[workspace.lints.clippy]
large_enum_variant = "allow"
too_many_arguments = "allow"
type_complexity = "allow"

[profile.production]
codegen-units = 1
inherits = "release"
lto = true


[profile.release]
opt-level = 3
panic = "unwind"
