[relaychain]
chain = "rococo-local"
default_command = "./bin-17.1/polkadot"

[[relaychain.nodes]]
name = "alice"
validator = true
rpc_port = 9900

[[relaychain.nodes]]
name = "bob"
validator = true

[[parachains]]
id = 1000
add_to_genesis = true
cumulus_based = true
chain = "asset-hub-rococo-local"

  [[parachains.collators]]
  name = "asset-hub-rococo-collator01"
  command = "./bin-17.1/polkadot-parachain"
  rpc_port = 9910
  args = ["-lxcm=trace,pallet-assets=trace"]

  [[parachains.collators]]
  name = "asset-hub-rococo-collator02"
  command = "./bin-17.1/polkadot-parachain"
  rpc_port = 9911
  args = ["--log=xcm=trace,pallet-assets=trace"]

[[parachains]]
id = 2000
addToGenesis = true
cumulus_based = true
chain = "dev"

[[parachains.collators]]
name = "collator01"
command = "./target/release/xcavate-node"
rpc_port = 9920
args = ["-lxcm=trace,pallet-assets=trace"]

[[parachains.collators]]
name = "collator02"
rpc_port = 9921
command = "./target/release/xcavate-node"
args = ["-lxcm=trace,pallet-assets=trace"]
