
//! Autogenerated weights for `delegation`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 48.0.0
//! DATE: 2026-02-13, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `recrafter-Legion-5-16IRX9`, CPU: `Intel(R) Core(TM) i7-14650HX`
//! WASM-EXECUTION: `Compiled`, CHAIN: `None`, DB CACHE: 1024

// Executed Command:
// ./target/release/xcavate-node
// benchmark
// pallet
// --pallet
// delegation
// --extrinsic
// *
// --steps
// 50
// --repeat
// 20
// --output
// ./runtime/src/weights/delegation.rs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use frame_support::{traits::Get, weights::Weight};
use core::marker::PhantomData;

/// Weight functions for `delegation`.
pub struct WeightInfo<T>(PhantomData<T>);
impl<T: frame_system::Config> delegation::WeightInfo for WeightInfo<T> {
	/// Storage: `Delegation::DelegationHierarchies` (r:1 w:1)
	/// Proof: `Delegation::DelegationHierarchies` (`max_values`: None, `max_size`: Some(80), added: 2555, mode: `MaxEncodedLen`)
	/// Storage: `Ctype::Ctypes` (r:1 w:0)
	/// Proof: `Ctype::Ctypes` (`max_values`: None, `max_size`: Some(84), added: 2559, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `Balances::Holds` (r:1 w:1)
	/// Proof: `Balances::Holds` (`max_values`: None, `max_size`: Some(463), added: 2938, mode: `MaxEncodedLen`)
	/// Storage: `Delegation::DelegationNodes` (r:0 w:1)
	/// Proof: `Delegation::DelegationNodes` (`max_values`: None, `max_size`: Some(32200), added: 34675, mode: `MaxEncodedLen`)
	/// Storage: `KiltMigration::MigratedKeys` (r:0 w:1)
	/// Proof: `KiltMigration::MigratedKeys` (`max_values`: None, `max_size`: Some(48), added: 2523, mode: `MaxEncodedLen`)
	fn create_hierarchy() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `392`
		//  Estimated: `3928`
		// Minimum execution time: 161_193_000 picoseconds.
		Weight::from_parts(229_702_000, 0)
			.saturating_add(Weight::from_parts(0, 3928))
			.saturating_add(T::DbWeight::get().reads(4))
			.saturating_add(T::DbWeight::get().writes(5))
	}
	/// Storage: `Delegation::DelegationNodes` (r:2 w:2)
	/// Proof: `Delegation::DelegationNodes` (`max_values`: None, `max_size`: Some(32200), added: 34675, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `Balances::Holds` (r:1 w:1)
	/// Proof: `Balances::Holds` (`max_values`: None, `max_size`: Some(463), added: 2938, mode: `MaxEncodedLen`)
	/// Storage: `KiltMigration::MigratedKeys` (r:0 w:1)
	/// Proof: `KiltMigration::MigratedKeys` (`max_values`: None, `max_size`: Some(48), added: 2523, mode: `MaxEncodedLen`)
	fn add_delegation() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `568`
		//  Estimated: `70340`
		// Minimum execution time: 106_439_000 picoseconds.
		Weight::from_parts(113_423_000, 0)
			.saturating_add(Weight::from_parts(0, 70340))
			.saturating_add(T::DbWeight::get().reads(4))
			.saturating_add(T::DbWeight::get().writes(5))
	}
	/// Storage: `Delegation::DelegationNodes` (r:5 w:5)
	/// Proof: `Delegation::DelegationNodes` (`max_values`: None, `max_size`: Some(32200), added: 34675, mode: `MaxEncodedLen`)
	/// Storage: `Delegation::DelegationHierarchies` (r:1 w:0)
	/// Proof: `Delegation::DelegationHierarchies` (`max_values`: None, `max_size`: Some(80), added: 2555, mode: `MaxEncodedLen`)
	/// The range of component `r` is `[1, 5]`.
	/// The range of component `c` is `[1, 5]`.
	fn revoke_delegation_root_child(r: u32, c: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `274 + r * (239 ±0)`
		//  Estimated: `3545 + r * (34675 ±0)`
		// Minimum execution time: 38_819_000 picoseconds.
		Weight::from_parts(21_622_907, 0)
			.saturating_add(Weight::from_parts(0, 3545))
			// Standard Error: 73_490
			.saturating_add(Weight::from_parts(18_321_892, 0).saturating_mul(r.into()))
			// Standard Error: 73_490
			.saturating_add(Weight::from_parts(992_443, 0).saturating_mul(c.into()))
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().reads((1_u64).saturating_mul(r.into())))
			.saturating_add(T::DbWeight::get().writes((1_u64).saturating_mul(r.into())))
			.saturating_add(Weight::from_parts(0, 34675).saturating_mul(r.into()))
	}
	/// Storage: `Delegation::DelegationNodes` (r:6 w:1)
	/// Proof: `Delegation::DelegationNodes` (`max_values`: None, `max_size`: Some(32200), added: 34675, mode: `MaxEncodedLen`)
	/// Storage: `Delegation::DelegationHierarchies` (r:1 w:0)
	/// Proof: `Delegation::DelegationHierarchies` (`max_values`: None, `max_size`: Some(80), added: 2555, mode: `MaxEncodedLen`)
	/// The range of component `r` is `[1, 5]`.
	/// The range of component `c` is `[1, 5]`.
	fn revoke_delegation_leaf(_r: u32, c: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `447 + c * (239 ±0)`
		//  Estimated: `35665 + c * (34675 ±0)`
		// Minimum execution time: 46_772_000 picoseconds.
		Weight::from_parts(44_144_241, 0)
			.saturating_add(Weight::from_parts(0, 35665))
			// Standard Error: 61_210
			.saturating_add(Weight::from_parts(7_669_568, 0).saturating_mul(c.into()))
			.saturating_add(T::DbWeight::get().reads(2))
			.saturating_add(T::DbWeight::get().reads((1_u64).saturating_mul(c.into())))
			.saturating_add(T::DbWeight::get().writes(1))
			.saturating_add(Weight::from_parts(0, 34675).saturating_mul(c.into()))
	}
	/// Storage: `Delegation::DelegationNodes` (r:6 w:6)
	/// Proof: `Delegation::DelegationNodes` (`max_values`: None, `max_size`: Some(32200), added: 34675, mode: `MaxEncodedLen`)
	/// Storage: `KiltMigration::MigratedKeys` (r:6 w:0)
	/// Proof: `KiltMigration::MigratedKeys` (`max_values`: None, `max_size`: Some(48), added: 2523, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `Balances::Holds` (r:1 w:1)
	/// Proof: `Balances::Holds` (`max_values`: None, `max_size`: Some(463), added: 2938, mode: `MaxEncodedLen`)
	/// Storage: `Delegation::DelegationHierarchies` (r:1 w:1)
	/// Proof: `Delegation::DelegationHierarchies` (`max_values`: None, `max_size`: Some(80), added: 2555, mode: `MaxEncodedLen`)
	/// The range of component `r` is `[1, 5]`.
	fn remove_delegation(r: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `716 + r * (294 ±0)`
		//  Estimated: `35665 + r * (34675 ±0)`
		// Minimum execution time: 170_191_000 picoseconds.
		Weight::from_parts(111_936_002, 0)
			.saturating_add(Weight::from_parts(0, 35665))
			// Standard Error: 121_198
			.saturating_add(Weight::from_parts(66_454_981, 0).saturating_mul(r.into()))
			.saturating_add(T::DbWeight::get().reads(5))
			.saturating_add(T::DbWeight::get().reads((2_u64).saturating_mul(r.into())))
			.saturating_add(T::DbWeight::get().writes(4))
			.saturating_add(T::DbWeight::get().writes((1_u64).saturating_mul(r.into())))
			.saturating_add(Weight::from_parts(0, 34675).saturating_mul(r.into()))
	}
	/// Storage: `Delegation::DelegationNodes` (r:6 w:6)
	/// Proof: `Delegation::DelegationNodes` (`max_values`: None, `max_size`: Some(32200), added: 34675, mode: `MaxEncodedLen`)
	/// Storage: `KiltMigration::MigratedKeys` (r:6 w:0)
	/// Proof: `KiltMigration::MigratedKeys` (`max_values`: None, `max_size`: Some(48), added: 2523, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `Balances::Holds` (r:1 w:1)
	/// Proof: `Balances::Holds` (`max_values`: None, `max_size`: Some(463), added: 2938, mode: `MaxEncodedLen`)
	/// Storage: `Delegation::DelegationHierarchies` (r:0 w:1)
	/// Proof: `Delegation::DelegationHierarchies` (`max_values`: None, `max_size`: Some(80), added: 2555, mode: `MaxEncodedLen`)
	/// The range of component `r` is `[1, 5]`.
	fn reclaim_deposit(r: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `648 + r * (294 ±0)`
		//  Estimated: `35665 + r * (34675 ±0)`
		// Minimum execution time: 160_963_000 picoseconds.
		Weight::from_parts(100_323_178, 0)
			.saturating_add(Weight::from_parts(0, 35665))
			// Standard Error: 63_321
			.saturating_add(Weight::from_parts(65_890_336, 0).saturating_mul(r.into()))
			.saturating_add(T::DbWeight::get().reads(4))
			.saturating_add(T::DbWeight::get().reads((2_u64).saturating_mul(r.into())))
			.saturating_add(T::DbWeight::get().writes(4))
			.saturating_add(T::DbWeight::get().writes((1_u64).saturating_mul(r.into())))
			.saturating_add(Weight::from_parts(0, 34675).saturating_mul(r.into()))
	}
	/// Storage: `Delegation::DelegationNodes` (r:1 w:0)
	/// Proof: `Delegation::DelegationNodes` (`max_values`: None, `max_size`: Some(32200), added: 34675, mode: `MaxEncodedLen`)
	/// Storage: `Delegation::DelegationHierarchies` (r:1 w:0)
	/// Proof: `Delegation::DelegationHierarchies` (`max_values`: None, `max_size`: Some(80), added: 2555, mode: `MaxEncodedLen`)
	fn can_attest() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `646`
		//  Estimated: `35665`
		// Minimum execution time: 20_301_000 picoseconds.
		Weight::from_parts(21_146_000, 0)
			.saturating_add(Weight::from_parts(0, 35665))
			.saturating_add(T::DbWeight::get().reads(2))
	}
	/// Storage: `Delegation::DelegationNodes` (r:6 w:0)
	/// Proof: `Delegation::DelegationNodes` (`max_values`: None, `max_size`: Some(32200), added: 34675, mode: `MaxEncodedLen`)
	/// The range of component `c` is `[1, 5]`.
	fn can_revoke(c: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `374 + c * (240 ±0)`
		//  Estimated: `35665 + c * (34675 ±0)`
		// Minimum execution time: 17_330_000 picoseconds.
		Weight::from_parts(12_889_000, 0)
			.saturating_add(Weight::from_parts(0, 35665))
			// Standard Error: 61_723
			.saturating_add(Weight::from_parts(7_389_438, 0).saturating_mul(c.into()))
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().reads((1_u64).saturating_mul(c.into())))
			.saturating_add(Weight::from_parts(0, 34675).saturating_mul(c.into()))
	}
	/// Storage: `Delegation::DelegationNodes` (r:6 w:0)
	/// Proof: `Delegation::DelegationNodes` (`max_values`: None, `max_size`: Some(32200), added: 34675, mode: `MaxEncodedLen`)
	/// The range of component `c` is `[1, 5]`.
	fn can_remove(c: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `374 + c * (240 ±0)`
		//  Estimated: `35665 + c * (34675 ±0)`
		// Minimum execution time: 17_332_000 picoseconds.
		Weight::from_parts(12_387_193, 0)
			.saturating_add(Weight::from_parts(0, 35665))
			// Standard Error: 53_543
			.saturating_add(Weight::from_parts(7_434_319, 0).saturating_mul(c.into()))
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().reads((1_u64).saturating_mul(c.into())))
			.saturating_add(Weight::from_parts(0, 34675).saturating_mul(c.into()))
	}
	/// Storage: `Delegation::DelegationNodes` (r:1 w:1)
	/// Proof: `Delegation::DelegationNodes` (`max_values`: None, `max_size`: Some(32200), added: 34675, mode: `MaxEncodedLen`)
	/// Storage: `KiltMigration::MigratedKeys` (r:1 w:0)
	/// Proof: `KiltMigration::MigratedKeys` (`max_values`: None, `max_size`: Some(48), added: 2523, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:2 w:2)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `Balances::Holds` (r:2 w:2)
	/// Proof: `Balances::Holds` (`max_values`: None, `max_size`: Some(463), added: 2938, mode: `MaxEncodedLen`)
	fn change_deposit_owner() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `890`
		//  Estimated: `35665`
		// Minimum execution time: 157_164_000 picoseconds.
		Weight::from_parts(160_638_000, 0)
			.saturating_add(Weight::from_parts(0, 35665))
			.saturating_add(T::DbWeight::get().reads(6))
			.saturating_add(T::DbWeight::get().writes(5))
	}
	/// Storage: `Delegation::DelegationNodes` (r:1 w:1)
	/// Proof: `Delegation::DelegationNodes` (`max_values`: None, `max_size`: Some(32200), added: 34675, mode: `MaxEncodedLen`)
	/// Storage: `KiltMigration::MigratedKeys` (r:1 w:0)
	/// Proof: `KiltMigration::MigratedKeys` (`max_values`: None, `max_size`: Some(48), added: 2523, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `Balances::Holds` (r:1 w:1)
	/// Proof: `Balances::Holds` (`max_values`: None, `max_size`: Some(463), added: 2938, mode: `MaxEncodedLen`)
	fn update_deposit() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `750`
		//  Estimated: `35665`
		// Minimum execution time: 138_145_000 picoseconds.
		Weight::from_parts(141_901_000, 0)
			.saturating_add(Weight::from_parts(0, 35665))
			.saturating_add(T::DbWeight::get().reads(4))
			.saturating_add(T::DbWeight::get().writes(3))
	}
}
