
//! Autogenerated weights for `did`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 48.0.0
//! DATE: 2026-02-13, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `recrafter-Legion-5-16IRX9`, CPU: `Intel(R) Core(TM) i7-14650HX`
//! WASM-EXECUTION: `Compiled`, CHAIN: `None`, DB CACHE: 1024

// Executed Command:
// ./target/release/xcavate-node
// benchmark
// pallet
// --pallet
// did
// --extrinsic
// *
// --steps
// 50
// --repeat
// 20
// --output
// ./runtime/src/weights/did.rs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use frame_support::{traits::Get, weights::Weight};
use core::marker::PhantomData;

/// Weight functions for `did`.
pub struct WeightInfo<T>(PhantomData<T>);
impl<T: frame_system::Config> did::WeightInfo for WeightInfo<T> {
	/// Storage: `Did::DidBlacklist` (r:1 w:0)
	/// Proof: `Did::DidBlacklist` (`max_values`: None, `max_size`: Some(48), added: 2523, mode: `MaxEncodedLen`)
	/// Storage: `Did::Did` (r:1 w:1)
	/// Proof: `Did::Did` (`max_values`: None, `max_size`: Some(2264), added: 4739, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `Balances::Holds` (r:1 w:0)
	/// Proof: `Balances::Holds` (`max_values`: None, `max_size`: Some(463), added: 2938, mode: `MaxEncodedLen`)
	/// Storage: `Did::DidEndpointsCount` (r:0 w:1)
	/// Proof: `Did::DidEndpointsCount` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `Did::ServiceEndpoints` (r:0 w:25)
	/// Proof: `Did::ServiceEndpoints` (`max_values`: None, `max_size`: Some(4215), added: 6690, mode: `MaxEncodedLen`)
	/// Storage: `KiltMigration::MigratedKeys` (r:0 w:1)
	/// Proof: `KiltMigration::MigratedKeys` (`max_values`: None, `max_size`: Some(48), added: 2523, mode: `MaxEncodedLen`)
	/// The range of component `n` is `[1, 10]`.
	/// The range of component `c` is `[1, 25]`.
	fn create_ed25519_keys(n: u32, c: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `245`
		//  Estimated: `5729`
		// Minimum execution time: 241_253_000 picoseconds.
		Weight::from_parts(213_098_554, 0)
			.saturating_add(Weight::from_parts(0, 5729))
			// Standard Error: 136_301
			.saturating_add(Weight::from_parts(1_620_677, 0).saturating_mul(n.into()))
			// Standard Error: 52_698
			.saturating_add(Weight::from_parts(39_320_426, 0).saturating_mul(c.into()))
			.saturating_add(T::DbWeight::get().reads(4))
			.saturating_add(T::DbWeight::get().writes(4))
			.saturating_add(T::DbWeight::get().writes((1_u64).saturating_mul(c.into())))
	}
	/// Storage: `Did::DidBlacklist` (r:1 w:0)
	/// Proof: `Did::DidBlacklist` (`max_values`: None, `max_size`: Some(48), added: 2523, mode: `MaxEncodedLen`)
	/// Storage: `Did::Did` (r:1 w:1)
	/// Proof: `Did::Did` (`max_values`: None, `max_size`: Some(2264), added: 4739, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `Balances::Holds` (r:1 w:0)
	/// Proof: `Balances::Holds` (`max_values`: None, `max_size`: Some(463), added: 2938, mode: `MaxEncodedLen`)
	/// Storage: `Did::DidEndpointsCount` (r:0 w:1)
	/// Proof: `Did::DidEndpointsCount` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `Did::ServiceEndpoints` (r:0 w:25)
	/// Proof: `Did::ServiceEndpoints` (`max_values`: None, `max_size`: Some(4215), added: 6690, mode: `MaxEncodedLen`)
	/// Storage: `KiltMigration::MigratedKeys` (r:0 w:1)
	/// Proof: `KiltMigration::MigratedKeys` (`max_values`: None, `max_size`: Some(48), added: 2523, mode: `MaxEncodedLen`)
	/// The range of component `n` is `[1, 10]`.
	/// The range of component `c` is `[1, 25]`.
	fn create_sr25519_keys(n: u32, c: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `245`
		//  Estimated: `5729`
		// Minimum execution time: 227_945_000 picoseconds.
		Weight::from_parts(212_967_828, 0)
			.saturating_add(Weight::from_parts(0, 5729))
			// Standard Error: 126_115
			.saturating_add(Weight::from_parts(1_757_454, 0).saturating_mul(n.into()))
			// Standard Error: 48_760
			.saturating_add(Weight::from_parts(44_482_058, 0).saturating_mul(c.into()))
			.saturating_add(T::DbWeight::get().reads(4))
			.saturating_add(T::DbWeight::get().writes(4))
			.saturating_add(T::DbWeight::get().writes((1_u64).saturating_mul(c.into())))
	}
	/// Storage: `Did::DidBlacklist` (r:1 w:0)
	/// Proof: `Did::DidBlacklist` (`max_values`: None, `max_size`: Some(48), added: 2523, mode: `MaxEncodedLen`)
	/// Storage: `Did::Did` (r:1 w:1)
	/// Proof: `Did::Did` (`max_values`: None, `max_size`: Some(2264), added: 4739, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `Balances::Holds` (r:1 w:0)
	/// Proof: `Balances::Holds` (`max_values`: None, `max_size`: Some(463), added: 2938, mode: `MaxEncodedLen`)
	/// Storage: `Did::DidEndpointsCount` (r:0 w:1)
	/// Proof: `Did::DidEndpointsCount` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `Did::ServiceEndpoints` (r:0 w:25)
	/// Proof: `Did::ServiceEndpoints` (`max_values`: None, `max_size`: Some(4215), added: 6690, mode: `MaxEncodedLen`)
	/// Storage: `KiltMigration::MigratedKeys` (r:0 w:1)
	/// Proof: `KiltMigration::MigratedKeys` (`max_values`: None, `max_size`: Some(48), added: 2523, mode: `MaxEncodedLen`)
	/// The range of component `n` is `[1, 10]`.
	/// The range of component `c` is `[1, 25]`.
	fn create_ecdsa_keys(n: u32, c: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `245`
		//  Estimated: `5729`
		// Minimum execution time: 204_406_000 picoseconds.
		Weight::from_parts(155_588_507, 0)
			.saturating_add(Weight::from_parts(0, 5729))
			// Standard Error: 84_646
			.saturating_add(Weight::from_parts(1_864_099, 0).saturating_mul(n.into()))
			// Standard Error: 32_727
			.saturating_add(Weight::from_parts(34_164_608, 0).saturating_mul(c.into()))
			.saturating_add(T::DbWeight::get().reads(4))
			.saturating_add(T::DbWeight::get().writes(4))
			.saturating_add(T::DbWeight::get().writes((1_u64).saturating_mul(c.into())))
	}
	/// Storage: `Did::DidEndpointsCount` (r:1 w:1)
	/// Proof: `Did::DidEndpointsCount` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `Did::ServiceEndpoints` (r:25 w:25)
	/// Proof: `Did::ServiceEndpoints` (`max_values`: None, `max_size`: Some(4215), added: 6690, mode: `MaxEncodedLen`)
	/// Storage: `Did::Did` (r:1 w:1)
	/// Proof: `Did::Did` (`max_values`: None, `max_size`: Some(2264), added: 4739, mode: `MaxEncodedLen`)
	/// Storage: `KiltMigration::MigratedKeys` (r:1 w:0)
	/// Proof: `KiltMigration::MigratedKeys` (`max_values`: None, `max_size`: Some(48), added: 2523, mode: `MaxEncodedLen`)
	/// Storage: `Balances::Holds` (r:1 w:1)
	/// Proof: `Balances::Holds` (`max_values`: None, `max_size`: Some(463), added: 2938, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `Did::DidBlacklist` (r:0 w:1)
	/// Proof: `Did::DidBlacklist` (`max_values`: None, `max_size`: Some(48), added: 2523, mode: `MaxEncodedLen`)
	/// The range of component `c` is `[1, 25]`.
	fn delete(c: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `693 + c * (105 ±0)`
		//  Estimated: `5729 + c * (6690 ±0)`
		// Minimum execution time: 80_412_000 picoseconds.
		Weight::from_parts(81_280_883, 0)
			.saturating_add(Weight::from_parts(0, 5729))
			// Standard Error: 12_920
			.saturating_add(Weight::from_parts(2_547_506, 0).saturating_mul(c.into()))
			.saturating_add(T::DbWeight::get().reads(5))
			.saturating_add(T::DbWeight::get().reads((1_u64).saturating_mul(c.into())))
			.saturating_add(T::DbWeight::get().writes(5))
			.saturating_add(T::DbWeight::get().writes((1_u64).saturating_mul(c.into())))
			.saturating_add(Weight::from_parts(0, 6690).saturating_mul(c.into()))
	}
	/// Storage: `Did::Did` (r:1 w:1)
	/// Proof: `Did::Did` (`max_values`: None, `max_size`: Some(2264), added: 4739, mode: `MaxEncodedLen`)
	/// Storage: `Did::DidEndpointsCount` (r:1 w:1)
	/// Proof: `Did::DidEndpointsCount` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `Did::ServiceEndpoints` (r:25 w:25)
	/// Proof: `Did::ServiceEndpoints` (`max_values`: None, `max_size`: Some(4215), added: 6690, mode: `MaxEncodedLen`)
	/// Storage: `KiltMigration::MigratedKeys` (r:1 w:0)
	/// Proof: `KiltMigration::MigratedKeys` (`max_values`: None, `max_size`: Some(48), added: 2523, mode: `MaxEncodedLen`)
	/// Storage: `Balances::Holds` (r:1 w:1)
	/// Proof: `Balances::Holds` (`max_values`: None, `max_size`: Some(463), added: 2938, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `Did::DidBlacklist` (r:0 w:1)
	/// Proof: `Did::DidBlacklist` (`max_values`: None, `max_size`: Some(48), added: 2523, mode: `MaxEncodedLen`)
	/// The range of component `c` is `[1, 25]`.
	fn reclaim_deposit(c: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `693 + c * (105 ±0)`
		//  Estimated: `5729 + c * (6690 ±0)`
		// Minimum execution time: 84_719_000 picoseconds.
		Weight::from_parts(85_432_516, 0)
			.saturating_add(Weight::from_parts(0, 5729))
			// Standard Error: 14_631
			.saturating_add(Weight::from_parts(2_565_777, 0).saturating_mul(c.into()))
			.saturating_add(T::DbWeight::get().reads(5))
			.saturating_add(T::DbWeight::get().reads((1_u64).saturating_mul(c.into())))
			.saturating_add(T::DbWeight::get().writes(5))
			.saturating_add(T::DbWeight::get().writes((1_u64).saturating_mul(c.into())))
			.saturating_add(Weight::from_parts(0, 6690).saturating_mul(c.into()))
	}
	/// Storage: `Did::Did` (r:1 w:1)
	/// Proof: `Did::Did` (`max_values`: None, `max_size`: Some(2264), added: 4739, mode: `MaxEncodedLen`)
	fn submit_did_call_ed25519_key() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `381`
		//  Estimated: `5729`
		// Minimum execution time: 114_939_000 picoseconds.
		Weight::from_parts(117_502_000, 0)
			.saturating_add(Weight::from_parts(0, 5729))
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `Did::Did` (r:1 w:1)
	/// Proof: `Did::Did` (`max_values`: None, `max_size`: Some(2264), added: 4739, mode: `MaxEncodedLen`)
	fn submit_did_call_sr25519_key() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `381`
		//  Estimated: `5729`
		// Minimum execution time: 116_487_000 picoseconds.
		Weight::from_parts(118_839_000, 0)
			.saturating_add(Weight::from_parts(0, 5729))
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `Did::Did` (r:1 w:1)
	/// Proof: `Did::Did` (`max_values`: None, `max_size`: Some(2264), added: 4739, mode: `MaxEncodedLen`)
	fn submit_did_call_ecdsa_key() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `382`
		//  Estimated: `5729`
		// Minimum execution time: 84_421_000 picoseconds.
		Weight::from_parts(87_331_000, 0)
			.saturating_add(Weight::from_parts(0, 5729))
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `Did::Did` (r:1 w:1)
	/// Proof: `Did::Did` (`max_values`: None, `max_size`: Some(2264), added: 4739, mode: `MaxEncodedLen`)
	/// Storage: `Did::DidEndpointsCount` (r:1 w:0)
	/// Proof: `Did::DidEndpointsCount` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `KiltMigration::MigratedKeys` (r:1 w:0)
	/// Proof: `KiltMigration::MigratedKeys` (`max_values`: None, `max_size`: Some(48), added: 2523, mode: `MaxEncodedLen`)
	fn set_ed25519_authentication_key() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1608`
		//  Estimated: `5729`
		// Minimum execution time: 46_249_000 picoseconds.
		Weight::from_parts(48_380_000, 0)
			.saturating_add(Weight::from_parts(0, 5729))
			.saturating_add(T::DbWeight::get().reads(3))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `Did::Did` (r:1 w:1)
	/// Proof: `Did::Did` (`max_values`: None, `max_size`: Some(2264), added: 4739, mode: `MaxEncodedLen`)
	/// Storage: `Did::DidEndpointsCount` (r:1 w:0)
	/// Proof: `Did::DidEndpointsCount` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `KiltMigration::MigratedKeys` (r:1 w:0)
	/// Proof: `KiltMigration::MigratedKeys` (`max_values`: None, `max_size`: Some(48), added: 2523, mode: `MaxEncodedLen`)
	fn set_sr25519_authentication_key() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1608`
		//  Estimated: `5729`
		// Minimum execution time: 47_057_000 picoseconds.
		Weight::from_parts(48_437_000, 0)
			.saturating_add(Weight::from_parts(0, 5729))
			.saturating_add(T::DbWeight::get().reads(3))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `Did::Did` (r:1 w:1)
	/// Proof: `Did::Did` (`max_values`: None, `max_size`: Some(2264), added: 4739, mode: `MaxEncodedLen`)
	/// Storage: `Did::DidEndpointsCount` (r:1 w:0)
	/// Proof: `Did::DidEndpointsCount` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `KiltMigration::MigratedKeys` (r:1 w:0)
	/// Proof: `KiltMigration::MigratedKeys` (`max_values`: None, `max_size`: Some(48), added: 2523, mode: `MaxEncodedLen`)
	fn set_ecdsa_authentication_key() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1611`
		//  Estimated: `5729`
		// Minimum execution time: 46_623_000 picoseconds.
		Weight::from_parts(49_093_000, 0)
			.saturating_add(Weight::from_parts(0, 5729))
			.saturating_add(T::DbWeight::get().reads(3))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `Did::Did` (r:1 w:1)
	/// Proof: `Did::Did` (`max_values`: None, `max_size`: Some(2264), added: 4739, mode: `MaxEncodedLen`)
	/// Storage: `Did::DidEndpointsCount` (r:1 w:0)
	/// Proof: `Did::DidEndpointsCount` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `KiltMigration::MigratedKeys` (r:1 w:0)
	/// Proof: `KiltMigration::MigratedKeys` (`max_values`: None, `max_size`: Some(48), added: 2523, mode: `MaxEncodedLen`)
	fn set_ed25519_delegation_key() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1608`
		//  Estimated: `5729`
		// Minimum execution time: 46_797_000 picoseconds.
		Weight::from_parts(49_017_000, 0)
			.saturating_add(Weight::from_parts(0, 5729))
			.saturating_add(T::DbWeight::get().reads(3))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `Did::Did` (r:1 w:1)
	/// Proof: `Did::Did` (`max_values`: None, `max_size`: Some(2264), added: 4739, mode: `MaxEncodedLen`)
	/// Storage: `Did::DidEndpointsCount` (r:1 w:0)
	/// Proof: `Did::DidEndpointsCount` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `KiltMigration::MigratedKeys` (r:1 w:0)
	/// Proof: `KiltMigration::MigratedKeys` (`max_values`: None, `max_size`: Some(48), added: 2523, mode: `MaxEncodedLen`)
	fn set_sr25519_delegation_key() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1608`
		//  Estimated: `5729`
		// Minimum execution time: 46_742_000 picoseconds.
		Weight::from_parts(49_084_000, 0)
			.saturating_add(Weight::from_parts(0, 5729))
			.saturating_add(T::DbWeight::get().reads(3))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `Did::Did` (r:1 w:1)
	/// Proof: `Did::Did` (`max_values`: None, `max_size`: Some(2264), added: 4739, mode: `MaxEncodedLen`)
	/// Storage: `Did::DidEndpointsCount` (r:1 w:0)
	/// Proof: `Did::DidEndpointsCount` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `KiltMigration::MigratedKeys` (r:1 w:0)
	/// Proof: `KiltMigration::MigratedKeys` (`max_values`: None, `max_size`: Some(48), added: 2523, mode: `MaxEncodedLen`)
	fn set_ecdsa_delegation_key() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1611`
		//  Estimated: `5729`
		// Minimum execution time: 46_352_000 picoseconds.
		Weight::from_parts(48_173_000, 0)
			.saturating_add(Weight::from_parts(0, 5729))
			.saturating_add(T::DbWeight::get().reads(3))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `Did::Did` (r:1 w:1)
	/// Proof: `Did::Did` (`max_values`: None, `max_size`: Some(2264), added: 4739, mode: `MaxEncodedLen`)
	/// Storage: `Did::DidEndpointsCount` (r:1 w:0)
	/// Proof: `Did::DidEndpointsCount` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `KiltMigration::MigratedKeys` (r:1 w:0)
	/// Proof: `KiltMigration::MigratedKeys` (`max_values`: None, `max_size`: Some(48), added: 2523, mode: `MaxEncodedLen`)
	fn remove_ed25519_delegation_key() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1608`
		//  Estimated: `5729`
		// Minimum execution time: 43_945_000 picoseconds.
		Weight::from_parts(45_902_000, 0)
			.saturating_add(Weight::from_parts(0, 5729))
			.saturating_add(T::DbWeight::get().reads(3))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `Did::Did` (r:1 w:1)
	/// Proof: `Did::Did` (`max_values`: None, `max_size`: Some(2264), added: 4739, mode: `MaxEncodedLen`)
	/// Storage: `Did::DidEndpointsCount` (r:1 w:0)
	/// Proof: `Did::DidEndpointsCount` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `KiltMigration::MigratedKeys` (r:1 w:0)
	/// Proof: `KiltMigration::MigratedKeys` (`max_values`: None, `max_size`: Some(48), added: 2523, mode: `MaxEncodedLen`)
	fn remove_sr25519_delegation_key() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1608`
		//  Estimated: `5729`
		// Minimum execution time: 44_228_000 picoseconds.
		Weight::from_parts(45_975_000, 0)
			.saturating_add(Weight::from_parts(0, 5729))
			.saturating_add(T::DbWeight::get().reads(3))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `Did::Did` (r:1 w:1)
	/// Proof: `Did::Did` (`max_values`: None, `max_size`: Some(2264), added: 4739, mode: `MaxEncodedLen`)
	/// Storage: `Did::DidEndpointsCount` (r:1 w:0)
	/// Proof: `Did::DidEndpointsCount` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `KiltMigration::MigratedKeys` (r:1 w:0)
	/// Proof: `KiltMigration::MigratedKeys` (`max_values`: None, `max_size`: Some(48), added: 2523, mode: `MaxEncodedLen`)
	fn remove_ecdsa_delegation_key() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1611`
		//  Estimated: `5729`
		// Minimum execution time: 43_800_000 picoseconds.
		Weight::from_parts(44_860_000, 0)
			.saturating_add(Weight::from_parts(0, 5729))
			.saturating_add(T::DbWeight::get().reads(3))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `Did::Did` (r:1 w:1)
	/// Proof: `Did::Did` (`max_values`: None, `max_size`: Some(2264), added: 4739, mode: `MaxEncodedLen`)
	/// Storage: `Did::DidEndpointsCount` (r:1 w:0)
	/// Proof: `Did::DidEndpointsCount` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `KiltMigration::MigratedKeys` (r:1 w:0)
	/// Proof: `KiltMigration::MigratedKeys` (`max_values`: None, `max_size`: Some(48), added: 2523, mode: `MaxEncodedLen`)
	fn set_ed25519_attestation_key() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1608`
		//  Estimated: `5729`
		// Minimum execution time: 47_188_000 picoseconds.
		Weight::from_parts(48_967_000, 0)
			.saturating_add(Weight::from_parts(0, 5729))
			.saturating_add(T::DbWeight::get().reads(3))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `Did::Did` (r:1 w:1)
	/// Proof: `Did::Did` (`max_values`: None, `max_size`: Some(2264), added: 4739, mode: `MaxEncodedLen`)
	/// Storage: `Did::DidEndpointsCount` (r:1 w:0)
	/// Proof: `Did::DidEndpointsCount` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `KiltMigration::MigratedKeys` (r:1 w:0)
	/// Proof: `KiltMigration::MigratedKeys` (`max_values`: None, `max_size`: Some(48), added: 2523, mode: `MaxEncodedLen`)
	fn set_sr25519_attestation_key() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1608`
		//  Estimated: `5729`
		// Minimum execution time: 47_669_000 picoseconds.
		Weight::from_parts(49_421_000, 0)
			.saturating_add(Weight::from_parts(0, 5729))
			.saturating_add(T::DbWeight::get().reads(3))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `Did::Did` (r:1 w:1)
	/// Proof: `Did::Did` (`max_values`: None, `max_size`: Some(2264), added: 4739, mode: `MaxEncodedLen`)
	/// Storage: `Did::DidEndpointsCount` (r:1 w:0)
	/// Proof: `Did::DidEndpointsCount` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `KiltMigration::MigratedKeys` (r:1 w:0)
	/// Proof: `KiltMigration::MigratedKeys` (`max_values`: None, `max_size`: Some(48), added: 2523, mode: `MaxEncodedLen`)
	fn set_ecdsa_attestation_key() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1611`
		//  Estimated: `5729`
		// Minimum execution time: 46_079_000 picoseconds.
		Weight::from_parts(47_500_000, 0)
			.saturating_add(Weight::from_parts(0, 5729))
			.saturating_add(T::DbWeight::get().reads(3))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `Did::Did` (r:1 w:1)
	/// Proof: `Did::Did` (`max_values`: None, `max_size`: Some(2264), added: 4739, mode: `MaxEncodedLen`)
	/// Storage: `Did::DidEndpointsCount` (r:1 w:0)
	/// Proof: `Did::DidEndpointsCount` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `KiltMigration::MigratedKeys` (r:1 w:0)
	/// Proof: `KiltMigration::MigratedKeys` (`max_values`: None, `max_size`: Some(48), added: 2523, mode: `MaxEncodedLen`)
	fn remove_ed25519_attestation_key() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1608`
		//  Estimated: `5729`
		// Minimum execution time: 45_021_000 picoseconds.
		Weight::from_parts(46_524_000, 0)
			.saturating_add(Weight::from_parts(0, 5729))
			.saturating_add(T::DbWeight::get().reads(3))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `Did::Did` (r:1 w:1)
	/// Proof: `Did::Did` (`max_values`: None, `max_size`: Some(2264), added: 4739, mode: `MaxEncodedLen`)
	/// Storage: `Did::DidEndpointsCount` (r:1 w:0)
	/// Proof: `Did::DidEndpointsCount` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `KiltMigration::MigratedKeys` (r:1 w:0)
	/// Proof: `KiltMigration::MigratedKeys` (`max_values`: None, `max_size`: Some(48), added: 2523, mode: `MaxEncodedLen`)
	fn remove_sr25519_attestation_key() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1608`
		//  Estimated: `5729`
		// Minimum execution time: 44_793_000 picoseconds.
		Weight::from_parts(46_321_000, 0)
			.saturating_add(Weight::from_parts(0, 5729))
			.saturating_add(T::DbWeight::get().reads(3))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `Did::Did` (r:1 w:1)
	/// Proof: `Did::Did` (`max_values`: None, `max_size`: Some(2264), added: 4739, mode: `MaxEncodedLen`)
	/// Storage: `Did::DidEndpointsCount` (r:1 w:0)
	/// Proof: `Did::DidEndpointsCount` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `KiltMigration::MigratedKeys` (r:1 w:0)
	/// Proof: `KiltMigration::MigratedKeys` (`max_values`: None, `max_size`: Some(48), added: 2523, mode: `MaxEncodedLen`)
	fn remove_ecdsa_attestation_key() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1611`
		//  Estimated: `5729`
		// Minimum execution time: 44_344_000 picoseconds.
		Weight::from_parts(46_059_000, 0)
			.saturating_add(Weight::from_parts(0, 5729))
			.saturating_add(T::DbWeight::get().reads(3))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `Did::Did` (r:1 w:1)
	/// Proof: `Did::Did` (`max_values`: None, `max_size`: Some(2264), added: 4739, mode: `MaxEncodedLen`)
	/// Storage: `Did::DidEndpointsCount` (r:1 w:0)
	/// Proof: `Did::DidEndpointsCount` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `KiltMigration::MigratedKeys` (r:1 w:0)
	/// Proof: `KiltMigration::MigratedKeys` (`max_values`: None, `max_size`: Some(48), added: 2523, mode: `MaxEncodedLen`)
	fn add_ed25519_key_agreement_key() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1506`
		//  Estimated: `5729`
		// Minimum execution time: 45_073_000 picoseconds.
		Weight::from_parts(46_328_000, 0)
			.saturating_add(Weight::from_parts(0, 5729))
			.saturating_add(T::DbWeight::get().reads(3))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `Did::Did` (r:1 w:1)
	/// Proof: `Did::Did` (`max_values`: None, `max_size`: Some(2264), added: 4739, mode: `MaxEncodedLen`)
	/// Storage: `Did::DidEndpointsCount` (r:1 w:0)
	/// Proof: `Did::DidEndpointsCount` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `KiltMigration::MigratedKeys` (r:1 w:0)
	/// Proof: `KiltMigration::MigratedKeys` (`max_values`: None, `max_size`: Some(48), added: 2523, mode: `MaxEncodedLen`)
	fn add_sr25519_key_agreement_key() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1506`
		//  Estimated: `5729`
		// Minimum execution time: 45_292_000 picoseconds.
		Weight::from_parts(47_489_000, 0)
			.saturating_add(Weight::from_parts(0, 5729))
			.saturating_add(T::DbWeight::get().reads(3))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `Did::Did` (r:1 w:1)
	/// Proof: `Did::Did` (`max_values`: None, `max_size`: Some(2264), added: 4739, mode: `MaxEncodedLen`)
	/// Storage: `Did::DidEndpointsCount` (r:1 w:0)
	/// Proof: `Did::DidEndpointsCount` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `KiltMigration::MigratedKeys` (r:1 w:0)
	/// Proof: `KiltMigration::MigratedKeys` (`max_values`: None, `max_size`: Some(48), added: 2523, mode: `MaxEncodedLen`)
	fn add_ecdsa_key_agreement_key() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1509`
		//  Estimated: `5729`
		// Minimum execution time: 45_471_000 picoseconds.
		Weight::from_parts(47_410_000, 0)
			.saturating_add(Weight::from_parts(0, 5729))
			.saturating_add(T::DbWeight::get().reads(3))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `Did::Did` (r:1 w:1)
	/// Proof: `Did::Did` (`max_values`: None, `max_size`: Some(2264), added: 4739, mode: `MaxEncodedLen`)
	/// Storage: `Did::DidEndpointsCount` (r:1 w:0)
	/// Proof: `Did::DidEndpointsCount` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `KiltMigration::MigratedKeys` (r:1 w:0)
	/// Proof: `KiltMigration::MigratedKeys` (`max_values`: None, `max_size`: Some(48), added: 2523, mode: `MaxEncodedLen`)
	fn remove_ed25519_key_agreement_key() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1608`
		//  Estimated: `5729`
		// Minimum execution time: 43_821_000 picoseconds.
		Weight::from_parts(46_084_000, 0)
			.saturating_add(Weight::from_parts(0, 5729))
			.saturating_add(T::DbWeight::get().reads(3))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `Did::Did` (r:1 w:1)
	/// Proof: `Did::Did` (`max_values`: None, `max_size`: Some(2264), added: 4739, mode: `MaxEncodedLen`)
	/// Storage: `Did::DidEndpointsCount` (r:1 w:0)
	/// Proof: `Did::DidEndpointsCount` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `KiltMigration::MigratedKeys` (r:1 w:0)
	/// Proof: `KiltMigration::MigratedKeys` (`max_values`: None, `max_size`: Some(48), added: 2523, mode: `MaxEncodedLen`)
	fn remove_sr25519_key_agreement_key() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1608`
		//  Estimated: `5729`
		// Minimum execution time: 44_255_000 picoseconds.
		Weight::from_parts(45_894_000, 0)
			.saturating_add(Weight::from_parts(0, 5729))
			.saturating_add(T::DbWeight::get().reads(3))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `Did::Did` (r:1 w:1)
	/// Proof: `Did::Did` (`max_values`: None, `max_size`: Some(2264), added: 4739, mode: `MaxEncodedLen`)
	/// Storage: `Did::DidEndpointsCount` (r:1 w:0)
	/// Proof: `Did::DidEndpointsCount` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `KiltMigration::MigratedKeys` (r:1 w:0)
	/// Proof: `KiltMigration::MigratedKeys` (`max_values`: None, `max_size`: Some(48), added: 2523, mode: `MaxEncodedLen`)
	fn remove_ecdsa_key_agreement_key() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1611`
		//  Estimated: `5729`
		// Minimum execution time: 43_553_000 picoseconds.
		Weight::from_parts(46_158_000, 0)
			.saturating_add(Weight::from_parts(0, 5729))
			.saturating_add(T::DbWeight::get().reads(3))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `Did::Did` (r:1 w:1)
	/// Proof: `Did::Did` (`max_values`: None, `max_size`: Some(2264), added: 4739, mode: `MaxEncodedLen`)
	/// Storage: `Did::DidEndpointsCount` (r:1 w:1)
	/// Proof: `Did::DidEndpointsCount` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `Did::ServiceEndpoints` (r:1 w:1)
	/// Proof: `Did::ServiceEndpoints` (`max_values`: None, `max_size`: Some(4215), added: 6690, mode: `MaxEncodedLen`)
	/// Storage: `KiltMigration::MigratedKeys` (r:1 w:0)
	/// Proof: `KiltMigration::MigratedKeys` (`max_values`: None, `max_size`: Some(48), added: 2523, mode: `MaxEncodedLen`)
	fn add_service_endpoint() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1056`
		//  Estimated: `7680`
		// Minimum execution time: 72_258_000 picoseconds.
		Weight::from_parts(75_311_000, 0)
			.saturating_add(Weight::from_parts(0, 7680))
			.saturating_add(T::DbWeight::get().reads(4))
			.saturating_add(T::DbWeight::get().writes(3))
	}
	/// Storage: `Did::Did` (r:1 w:1)
	/// Proof: `Did::Did` (`max_values`: None, `max_size`: Some(2264), added: 4739, mode: `MaxEncodedLen`)
	/// Storage: `Did::ServiceEndpoints` (r:1 w:1)
	/// Proof: `Did::ServiceEndpoints` (`max_values`: None, `max_size`: Some(4215), added: 6690, mode: `MaxEncodedLen`)
	/// Storage: `Did::DidEndpointsCount` (r:1 w:1)
	/// Proof: `Did::DidEndpointsCount` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `KiltMigration::MigratedKeys` (r:1 w:0)
	/// Proof: `KiltMigration::MigratedKeys` (`max_values`: None, `max_size`: Some(48), added: 2523, mode: `MaxEncodedLen`)
	fn remove_service_endpoint() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `5239`
		//  Estimated: `7680`
		// Minimum execution time: 65_988_000 picoseconds.
		Weight::from_parts(69_080_000, 0)
			.saturating_add(Weight::from_parts(0, 7680))
			.saturating_add(T::DbWeight::get().reads(4))
			.saturating_add(T::DbWeight::get().writes(3))
	}
	/// Storage: `Did::Did` (r:1 w:0)
	/// Proof: `Did::Did` (`max_values`: None, `max_size`: Some(2264), added: 4739, mode: `MaxEncodedLen`)
	/// The range of component `l` is `[1, 5242880]`.
	fn signature_verification_sr25519(l: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1607`
		//  Estimated: `5729`
		// Minimum execution time: 101_640_000 picoseconds.
		Weight::from_parts(56_599_998, 0)
			.saturating_add(Weight::from_parts(0, 5729))
			// Standard Error: 1
			.saturating_add(Weight::from_parts(4_637, 0).saturating_mul(l.into()))
			.saturating_add(T::DbWeight::get().reads(1))
	}
	/// Storage: `Did::Did` (r:1 w:0)
	/// Proof: `Did::Did` (`max_values`: None, `max_size`: Some(2264), added: 4739, mode: `MaxEncodedLen`)
	/// The range of component `l` is `[1, 5242880]`.
	fn signature_verification_ed25519(l: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1607`
		//  Estimated: `5729`
		// Minimum execution time: 97_900_000 picoseconds.
		Weight::from_parts(74_958_969, 0)
			.saturating_add(Weight::from_parts(0, 5729))
			// Standard Error: 1
			.saturating_add(Weight::from_parts(3_240, 0).saturating_mul(l.into()))
			.saturating_add(T::DbWeight::get().reads(1))
	}
	/// Storage: `Did::Did` (r:1 w:0)
	/// Proof: `Did::Did` (`max_values`: None, `max_size`: Some(2264), added: 4739, mode: `MaxEncodedLen`)
	/// The range of component `l` is `[1, 5242880]`.
	fn signature_verification_ecdsa(l: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1608`
		//  Estimated: `5729`
		// Minimum execution time: 73_283_000 picoseconds.
		Weight::from_parts(27_322_786, 0)
			.saturating_add(Weight::from_parts(0, 5729))
			// Standard Error: 1
			.saturating_add(Weight::from_parts(1_977, 0).saturating_mul(l.into()))
			.saturating_add(T::DbWeight::get().reads(1))
	}
	/// Storage: `KiltMigration::MigratedKeys` (r:1 w:1)
	/// Proof: `KiltMigration::MigratedKeys` (`max_values`: None, `max_size`: Some(48), added: 2523, mode: `MaxEncodedLen`)
	/// Storage: `Did::Did` (r:1 w:1)
	/// Proof: `Did::Did` (`max_values`: None, `max_size`: Some(2264), added: 4739, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `Balances::Holds` (r:1 w:0)
	/// Proof: `Balances::Holds` (`max_values`: None, `max_size`: Some(463), added: 2938, mode: `MaxEncodedLen`)
	fn change_deposit_owner() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `487`
		//  Estimated: `5729`
		// Minimum execution time: 76_404_000 picoseconds.
		Weight::from_parts(79_716_000, 0)
			.saturating_add(Weight::from_parts(0, 5729))
			.saturating_add(T::DbWeight::get().reads(4))
			.saturating_add(T::DbWeight::get().writes(3))
	}
	/// Storage: `Did::Did` (r:1 w:1)
	/// Proof: `Did::Did` (`max_values`: None, `max_size`: Some(2264), added: 4739, mode: `MaxEncodedLen`)
	/// Storage: `Did::DidEndpointsCount` (r:1 w:0)
	/// Proof: `Did::DidEndpointsCount` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `KiltMigration::MigratedKeys` (r:1 w:0)
	/// Proof: `KiltMigration::MigratedKeys` (`max_values`: None, `max_size`: Some(48), added: 2523, mode: `MaxEncodedLen`)
	fn update_deposit() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `384`
		//  Estimated: `5729`
		// Minimum execution time: 29_789_000 picoseconds.
		Weight::from_parts(36_030_000, 0)
			.saturating_add(Weight::from_parts(0, 5729))
			.saturating_add(T::DbWeight::get().reads(3))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `Did::Did` (r:1 w:0)
	/// Proof: `Did::Did` (`max_values`: None, `max_size`: Some(2264), added: 4739, mode: `MaxEncodedLen`)
	fn dispatch_as() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `382`
		//  Estimated: `5729`
		// Minimum execution time: 28_282_000 picoseconds.
		Weight::from_parts(64_956_000, 0)
			.saturating_add(Weight::from_parts(0, 5729))
			.saturating_add(T::DbWeight::get().reads(1))
	}
	/// Storage: `Did::DidBlacklist` (r:1 w:0)
	/// Proof: `Did::DidBlacklist` (`max_values`: None, `max_size`: Some(48), added: 2523, mode: `MaxEncodedLen`)
	/// Storage: `Did::Did` (r:1 w:1)
	/// Proof: `Did::Did` (`max_values`: None, `max_size`: Some(2264), added: 4739, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `Balances::Holds` (r:1 w:0)
	/// Proof: `Balances::Holds` (`max_values`: None, `max_size`: Some(463), added: 2938, mode: `MaxEncodedLen`)
	/// Storage: `KiltMigration::MigratedKeys` (r:0 w:1)
	/// Proof: `KiltMigration::MigratedKeys` (`max_values`: None, `max_size`: Some(48), added: 2523, mode: `MaxEncodedLen`)
	fn create_from_account() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `245`
		//  Estimated: `5729`
		// Minimum execution time: 91_956_000 picoseconds.
		Weight::from_parts(106_792_000, 0)
			.saturating_add(Weight::from_parts(0, 5729))
			.saturating_add(T::DbWeight::get().reads(4))
			.saturating_add(T::DbWeight::get().writes(3))
	}
}
