
//! Autogenerated weights for `pallet_property_governance`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 48.0.0
//! DATE: 2026-06-15, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `recrafter-Legion-5-16IRX9`, CPU: `Intel(R) Core(TM) i7-14650HX`
//! WASM-EXECUTION: `Compiled`, CHAIN: `None`, DB CACHE: 1024

// Executed Command:
// ./target/release/xcavate-node
// benchmark
// pallet
// --pallet
// pallet_property_governance
// --extrinsic
// *
// --steps
// 50
// --repeat
// 20
// --output
// ./runtime/src/weights/pallet_property_governance.rs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use frame_support::{traits::Get, weights::Weight};
use core::marker::PhantomData;

/// Weight functions for `pallet_property_governance`.
pub struct WeightInfo<T>(PhantomData<T>);
impl<T: frame_system::Config> pallet_property_governance::WeightInfo for WeightInfo<T> {
	/// Storage: `XcavateWhitelist::AccountRoles` (r:1 w:0)
	/// Proof: `XcavateWhitelist::AccountRoles` (`max_values`: None, `max_size`: Some(66), added: 2541, mode: `MaxEncodedLen`)
	/// Storage: `PropertyManagement::LettingStorage` (r:1 w:0)
	/// Proof: `PropertyManagement::LettingStorage` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `PropertyGovernance::AssetProposal` (r:1 w:1)
	/// Proof: `PropertyGovernance::AssetProposal` (`max_values`: None, `max_size`: Some(28), added: 2503, mode: `MaxEncodedLen`)
	/// Storage: `PropertyGovernance::ProposalCount` (r:1 w:1)
	/// Proof: `PropertyGovernance::ProposalCount` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `PropertyGovernance::ProposalRoundsExpiring` (r:1 w:1)
	/// Proof: `PropertyGovernance::ProposalRoundsExpiring` (`max_values`: None, `max_size`: Some(422), added: 2897, mode: `MaxEncodedLen`)
	/// Storage: `PropertyGovernance::OngoingProposalVotes` (r:0 w:1)
	/// Proof: `PropertyGovernance::OngoingProposalVotes` (`max_values`: None, `max_size`: Some(36), added: 2511, mode: `MaxEncodedLen`)
	/// Storage: `PropertyGovernance::Proposals` (r:0 w:1)
	/// Proof: `PropertyGovernance::Proposals` (`max_values`: None, `max_size`: Some(5078), added: 7553, mode: `MaxEncodedLen`)
	fn propose() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1890`
		//  Estimated: `3887`
		// Minimum execution time: 82_132_000 picoseconds.
		Weight::from_parts(95_193_000, 0)
			.saturating_add(Weight::from_parts(0, 3887))
			.saturating_add(T::DbWeight::get().reads(5))
			.saturating_add(T::DbWeight::get().writes(5))
	}
	/// Storage: `XcavateWhitelist::AccountRoles` (r:1 w:0)
	/// Proof: `XcavateWhitelist::AccountRoles` (`max_values`: None, `max_size`: Some(66), added: 2541, mode: `MaxEncodedLen`)
	/// Storage: `RealWorldAsset::PropertyOwner` (r:1 w:0)
	/// Proof: `RealWorldAsset::PropertyOwner` (`max_values`: None, `max_size`: Some(8022), added: 10497, mode: `MaxEncodedLen`)
	/// Storage: `PropertyManagement::LettingStorage` (r:1 w:0)
	/// Proof: `PropertyManagement::LettingStorage` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `PropertyGovernance::AssetLettingChallenge` (r:1 w:1)
	/// Proof: `PropertyGovernance::AssetLettingChallenge` (`max_values`: None, `max_size`: Some(28), added: 2503, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `Balances::Holds` (r:1 w:1)
	/// Proof: `Balances::Holds` (`max_values`: None, `max_size`: Some(499), added: 2974, mode: `MaxEncodedLen`)
	/// Storage: `PropertyGovernance::ProposalCount` (r:1 w:1)
	/// Proof: `PropertyGovernance::ProposalCount` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `PropertyGovernance::ChallengeRoundsExpiring` (r:1 w:1)
	/// Proof: `PropertyGovernance::ChallengeRoundsExpiring` (`max_values`: None, `max_size`: Some(422), added: 2897, mode: `MaxEncodedLen`)
	/// Storage: `PropertyGovernance::OngoingChallengeVotes` (r:0 w:1)
	/// Proof: `PropertyGovernance::OngoingChallengeVotes` (`max_values`: None, `max_size`: Some(36), added: 2511, mode: `MaxEncodedLen`)
	/// Storage: `PropertyGovernance::Challenges` (r:0 w:1)
	/// Proof: `PropertyGovernance::Challenges` (`max_values`: None, `max_size`: Some(76), added: 2551, mode: `MaxEncodedLen`)
	fn challenge_against_letting_agent() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `10831`
		//  Estimated: `11487`
		// Minimum execution time: 155_413_000 picoseconds.
		Weight::from_parts(169_505_000, 0)
			.saturating_add(Weight::from_parts(0, 11487))
			.saturating_add(T::DbWeight::get().reads(8))
			.saturating_add(T::DbWeight::get().writes(7))
	}
	/// Storage: `XcavateWhitelist::AccountRoles` (r:1 w:0)
	/// Proof: `XcavateWhitelist::AccountRoles` (`max_values`: None, `max_size`: Some(66), added: 2541, mode: `MaxEncodedLen`)
	/// Storage: `PropertyGovernance::AssetProposal` (r:1 w:0)
	/// Proof: `PropertyGovernance::AssetProposal` (`max_values`: None, `max_size`: Some(28), added: 2503, mode: `MaxEncodedLen`)
	/// Storage: `PropertyGovernance::Proposals` (r:1 w:0)
	/// Proof: `PropertyGovernance::Proposals` (`max_values`: None, `max_size`: Some(5078), added: 7553, mode: `MaxEncodedLen`)
	/// Storage: `RealWorldAsset::PropertyOwner` (r:1 w:0)
	/// Proof: `RealWorldAsset::PropertyOwner` (`max_values`: None, `max_size`: Some(8022), added: 10497, mode: `MaxEncodedLen`)
	/// Storage: `RealWorldAsset::PropertyOwnerToken` (r:1 w:0)
	/// Proof: `RealWorldAsset::PropertyOwnerToken` (`max_values`: None, `max_size`: Some(72), added: 2547, mode: `MaxEncodedLen`)
	/// Storage: `PropertyGovernance::OngoingProposalVotes` (r:1 w:1)
	/// Proof: `PropertyGovernance::OngoingProposalVotes` (`max_values`: None, `max_size`: Some(36), added: 2511, mode: `MaxEncodedLen`)
	/// Storage: `PropertyGovernance::UserProposalVote` (r:1 w:1)
	/// Proof: `PropertyGovernance::UserProposalVote` (`max_values`: None, `max_size`: Some(81), added: 2556, mode: `MaxEncodedLen`)
	/// Storage: `AssetsFreezer::Freezes` (r:1 w:1)
	/// Proof: `AssetsFreezer::Freezes` (`max_values`: None, `max_size`: Some(137), added: 2612, mode: `MaxEncodedLen`)
	/// Storage: `RealEstateAssets::Account` (r:1 w:0)
	/// Proof: `RealEstateAssets::Account` (`max_values`: None, `max_size`: Some(134), added: 2609, mode: `MaxEncodedLen`)
	/// Storage: `AssetsFreezer::FrozenBalances` (r:1 w:1)
	/// Proof: `AssetsFreezer::FrozenBalances` (`max_values`: None, `max_size`: Some(84), added: 2559, mode: `MaxEncodedLen`)
	fn vote_on_proposal() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `13776`
		//  Estimated: `11487`
		// Minimum execution time: 159_636_000 picoseconds.
		Weight::from_parts(170_456_000, 0)
			.saturating_add(Weight::from_parts(0, 11487))
			.saturating_add(T::DbWeight::get().reads(10))
			.saturating_add(T::DbWeight::get().writes(4))
	}
	/// Storage: `PropertyGovernance::UserProposalVote` (r:1 w:1)
	/// Proof: `PropertyGovernance::UserProposalVote` (`max_values`: None, `max_size`: Some(81), added: 2556, mode: `MaxEncodedLen`)
	/// Storage: `PropertyGovernance::Proposals` (r:1 w:0)
	/// Proof: `PropertyGovernance::Proposals` (`max_values`: None, `max_size`: Some(5078), added: 7553, mode: `MaxEncodedLen`)
	/// Storage: `AssetsFreezer::Freezes` (r:1 w:1)
	/// Proof: `AssetsFreezer::Freezes` (`max_values`: None, `max_size`: Some(137), added: 2612, mode: `MaxEncodedLen`)
	/// Storage: `RealEstateAssets::Account` (r:1 w:0)
	/// Proof: `RealEstateAssets::Account` (`max_values`: None, `max_size`: Some(134), added: 2609, mode: `MaxEncodedLen`)
	/// Storage: `AssetsFreezer::FrozenBalances` (r:1 w:1)
	/// Proof: `AssetsFreezer::FrozenBalances` (`max_values`: None, `max_size`: Some(84), added: 2559, mode: `MaxEncodedLen`)
	fn unfreeze_proposal_token() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `4197`
		//  Estimated: `8543`
		// Minimum execution time: 77_210_000 picoseconds.
		Weight::from_parts(86_755_000, 0)
			.saturating_add(Weight::from_parts(0, 8543))
			.saturating_add(T::DbWeight::get().reads(5))
			.saturating_add(T::DbWeight::get().writes(3))
	}
	/// Storage: `XcavateWhitelist::AccountRoles` (r:1 w:0)
	/// Proof: `XcavateWhitelist::AccountRoles` (`max_values`: None, `max_size`: Some(66), added: 2541, mode: `MaxEncodedLen`)
	/// Storage: `PropertyGovernance::AssetLettingChallenge` (r:1 w:0)
	/// Proof: `PropertyGovernance::AssetLettingChallenge` (`max_values`: None, `max_size`: Some(28), added: 2503, mode: `MaxEncodedLen`)
	/// Storage: `PropertyGovernance::Challenges` (r:1 w:0)
	/// Proof: `PropertyGovernance::Challenges` (`max_values`: None, `max_size`: Some(76), added: 2551, mode: `MaxEncodedLen`)
	/// Storage: `RealWorldAsset::PropertyOwner` (r:1 w:0)
	/// Proof: `RealWorldAsset::PropertyOwner` (`max_values`: None, `max_size`: Some(8022), added: 10497, mode: `MaxEncodedLen`)
	/// Storage: `RealWorldAsset::PropertyOwnerToken` (r:1 w:0)
	/// Proof: `RealWorldAsset::PropertyOwnerToken` (`max_values`: None, `max_size`: Some(72), added: 2547, mode: `MaxEncodedLen`)
	/// Storage: `PropertyGovernance::OngoingChallengeVotes` (r:1 w:1)
	/// Proof: `PropertyGovernance::OngoingChallengeVotes` (`max_values`: None, `max_size`: Some(36), added: 2511, mode: `MaxEncodedLen`)
	/// Storage: `PropertyGovernance::UserChallengeVote` (r:1 w:1)
	/// Proof: `PropertyGovernance::UserChallengeVote` (`max_values`: None, `max_size`: Some(81), added: 2556, mode: `MaxEncodedLen`)
	/// Storage: `AssetsFreezer::Freezes` (r:1 w:1)
	/// Proof: `AssetsFreezer::Freezes` (`max_values`: None, `max_size`: Some(137), added: 2612, mode: `MaxEncodedLen`)
	/// Storage: `RealEstateAssets::Account` (r:1 w:0)
	/// Proof: `RealEstateAssets::Account` (`max_values`: None, `max_size`: Some(134), added: 2609, mode: `MaxEncodedLen`)
	/// Storage: `AssetsFreezer::FrozenBalances` (r:1 w:1)
	/// Proof: `AssetsFreezer::FrozenBalances` (`max_values`: None, `max_size`: Some(84), added: 2559, mode: `MaxEncodedLen`)
	fn vote_on_letting_agent_challenge() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `13771`
		//  Estimated: `11487`
		// Minimum execution time: 149_805_000 picoseconds.
		Weight::from_parts(167_637_000, 0)
			.saturating_add(Weight::from_parts(0, 11487))
			.saturating_add(T::DbWeight::get().reads(10))
			.saturating_add(T::DbWeight::get().writes(4))
	}
	/// Storage: `PropertyGovernance::UserChallengeVote` (r:1 w:1)
	/// Proof: `PropertyGovernance::UserChallengeVote` (`max_values`: None, `max_size`: Some(81), added: 2556, mode: `MaxEncodedLen`)
	/// Storage: `PropertyGovernance::Challenges` (r:1 w:0)
	/// Proof: `PropertyGovernance::Challenges` (`max_values`: None, `max_size`: Some(76), added: 2551, mode: `MaxEncodedLen`)
	/// Storage: `AssetsFreezer::Freezes` (r:1 w:1)
	/// Proof: `AssetsFreezer::Freezes` (`max_values`: None, `max_size`: Some(137), added: 2612, mode: `MaxEncodedLen`)
	/// Storage: `RealEstateAssets::Account` (r:1 w:0)
	/// Proof: `RealEstateAssets::Account` (`max_values`: None, `max_size`: Some(134), added: 2609, mode: `MaxEncodedLen`)
	/// Storage: `AssetsFreezer::FrozenBalances` (r:1 w:1)
	/// Proof: `AssetsFreezer::FrozenBalances` (`max_values`: None, `max_size`: Some(84), added: 2559, mode: `MaxEncodedLen`)
	fn unfreeze_challenge_token() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `4197`
		//  Estimated: `3602`
		// Minimum execution time: 77_176_000 picoseconds.
		Weight::from_parts(85_068_000, 0)
			.saturating_add(Weight::from_parts(0, 3602))
			.saturating_add(T::DbWeight::get().reads(5))
			.saturating_add(T::DbWeight::get().writes(3))
	}
}
