
//! Autogenerated weights for `pallet_education_regions`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 48.0.0
//! DATE: 2026-06-15, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `recrafter-Legion-5-16IRX9`, CPU: `Intel(R) Core(TM) i7-14650HX`
//! WASM-EXECUTION: `Compiled`, CHAIN: `None`, DB CACHE: 1024

// Executed Command:
// ./target/release/xcavate-node
// benchmark
// pallet
// --pallet
// pallet_education_regions
// --extrinsic
// *
// --steps
// 50
// --repeat
// 20
// --output
// ./runtime/src/weights/pallet_education_regions.rs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use frame_support::{traits::Get, weights::Weight};
use core::marker::PhantomData;

/// Weight functions for `pallet_education_regions`.
pub struct WeightInfo<T>(PhantomData<T>);
impl<T: frame_system::Config> pallet_education_regions::WeightInfo for WeightInfo<T> {
	/// Storage: `XcavateWhitelist::AccountRoles` (r:1 w:0)
	/// Proof: `XcavateWhitelist::AccountRoles` (`max_values`: None, `max_size`: Some(66), added: 2541, mode: `MaxEncodedLen`)
	/// Storage: `EducationRegions::RegionProposalId` (r:1 w:1)
	/// Proof: `EducationRegions::RegionProposalId` (`max_values`: None, `max_size`: Some(26), added: 2501, mode: `MaxEncodedLen`)
	/// Storage: `EducationRegions::RegionDetails` (r:1 w:0)
	/// Proof: `EducationRegions::RegionDetails` (`max_values`: None, `max_size`: Some(71), added: 2546, mode: `MaxEncodedLen`)
	/// Storage: `EducationRegions::ProposalCounter` (r:1 w:1)
	/// Proof: `EducationRegions::ProposalCounter` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `Balances::Holds` (r:1 w:1)
	/// Proof: `Balances::Holds` (`max_values`: None, `max_size`: Some(499), added: 2974, mode: `MaxEncodedLen`)
	/// Storage: `EducationRegions::RegionProposals` (r:0 w:1)
	/// Proof: `EducationRegions::RegionProposals` (`max_values`: None, `max_size`: Some(80), added: 2555, mode: `MaxEncodedLen`)
	/// Storage: `EducationRegions::LastRegionProposalBlock` (r:0 w:1)
	/// Proof: `EducationRegions::LastRegionProposalBlock` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `EducationRegions::OngoingRegionProposalVotes` (r:0 w:1)
	/// Proof: `EducationRegions::OngoingRegionProposalVotes` (`max_values`: None, `max_size`: Some(72), added: 2547, mode: `MaxEncodedLen`)
	fn propose_new_region() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `378`
		//  Estimated: `3964`
		// Minimum execution time: 62_202_000 picoseconds.
		Weight::from_parts(63_089_000, 0)
			.saturating_add(Weight::from_parts(0, 3964))
			.saturating_add(T::DbWeight::get().reads(5))
			.saturating_add(T::DbWeight::get().writes(6))
	}
	/// Storage: `EducationRegions::RegionProposalId` (r:1 w:0)
	/// Proof: `EducationRegions::RegionProposalId` (`max_values`: None, `max_size`: Some(26), added: 2501, mode: `MaxEncodedLen`)
	/// Storage: `EducationRegions::RegionProposals` (r:1 w:0)
	/// Proof: `EducationRegions::RegionProposals` (`max_values`: None, `max_size`: Some(80), added: 2555, mode: `MaxEncodedLen`)
	/// Storage: `Balances::Holds` (r:1 w:1)
	/// Proof: `Balances::Holds` (`max_values`: None, `max_size`: Some(499), added: 2974, mode: `MaxEncodedLen`)
	/// Storage: `EducationRegions::OngoingRegionProposalVotes` (r:1 w:1)
	/// Proof: `EducationRegions::OngoingRegionProposalVotes` (`max_values`: None, `max_size`: Some(72), added: 2547, mode: `MaxEncodedLen`)
	/// Storage: `EducationRegions::UserRegionVote` (r:1 w:1)
	/// Proof: `EducationRegions::UserRegionVote` (`max_values`: None, `max_size`: Some(91), added: 2566, mode: `MaxEncodedLen`)
	fn vote_on_region_proposal() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `624`
		//  Estimated: `3964`
		// Minimum execution time: 86_017_000 picoseconds.
		Weight::from_parts(87_117_000, 0)
			.saturating_add(Weight::from_parts(0, 3964))
			.saturating_add(T::DbWeight::get().reads(5))
			.saturating_add(T::DbWeight::get().writes(3))
	}
	/// Storage: `EducationRegions::UserRegionVote` (r:1 w:1)
	/// Proof: `EducationRegions::UserRegionVote` (`max_values`: None, `max_size`: Some(91), added: 2566, mode: `MaxEncodedLen`)
	/// Storage: `EducationRegions::RegionProposals` (r:1 w:0)
	/// Proof: `EducationRegions::RegionProposals` (`max_values`: None, `max_size`: Some(80), added: 2555, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `Balances::Holds` (r:1 w:1)
	/// Proof: `Balances::Holds` (`max_values`: None, `max_size`: Some(499), added: 2974, mode: `MaxEncodedLen`)
	fn unlock_region_voting_token() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `492`
		//  Estimated: `3964`
		// Minimum execution time: 48_912_000 picoseconds.
		Weight::from_parts(50_107_000, 0)
			.saturating_add(Weight::from_parts(0, 3964))
			.saturating_add(T::DbWeight::get().reads(4))
			.saturating_add(T::DbWeight::get().writes(3))
	}
	/// Storage: `XcavateWhitelist::AccountRoles` (r:1 w:0)
	/// Proof: `XcavateWhitelist::AccountRoles` (`max_values`: None, `max_size`: Some(66), added: 2541, mode: `MaxEncodedLen`)
	/// Storage: `EducationRegions::RegionProposalId` (r:1 w:0)
	/// Proof: `EducationRegions::RegionProposalId` (`max_values`: None, `max_size`: Some(26), added: 2501, mode: `MaxEncodedLen`)
	/// Storage: `EducationRegions::RegionProposals` (r:1 w:0)
	/// Proof: `EducationRegions::RegionProposals` (`max_values`: None, `max_size`: Some(80), added: 2555, mode: `MaxEncodedLen`)
	/// Storage: `EducationRegions::RegionAuctions` (r:1 w:1)
	/// Proof: `EducationRegions::RegionAuctions` (`max_values`: None, `max_size`: Some(71), added: 2546, mode: `MaxEncodedLen`)
	/// Storage: `Balances::Holds` (r:2 w:2)
	/// Proof: `Balances::Holds` (`max_values`: None, `max_size`: Some(499), added: 2974, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	fn bid_on_region() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `3989`
		//  Estimated: `6938`
		// Minimum execution time: 122_206_000 picoseconds.
		Weight::from_parts(134_461_000, 0)
			.saturating_add(Weight::from_parts(0, 6938))
			.saturating_add(T::DbWeight::get().reads(7))
			.saturating_add(T::DbWeight::get().writes(4))
	}
	/// Storage: `XcavateWhitelist::AccountRoles` (r:1 w:0)
	/// Proof: `XcavateWhitelist::AccountRoles` (`max_values`: None, `max_size`: Some(66), added: 2541, mode: `MaxEncodedLen`)
	/// Storage: `EducationRegions::RegionAuctions` (r:1 w:1)
	/// Proof: `EducationRegions::RegionAuctions` (`max_values`: None, `max_size`: Some(71), added: 2546, mode: `MaxEncodedLen`)
	/// Storage: `EducationRegions::RegionProposalId` (r:0 w:1)
	/// Proof: `EducationRegions::RegionProposalId` (`max_values`: None, `max_size`: Some(26), added: 2501, mode: `MaxEncodedLen`)
	/// Storage: `EducationRegions::RegionDetails` (r:0 w:1)
	/// Proof: `EducationRegions::RegionDetails` (`max_values`: None, `max_size`: Some(71), added: 2546, mode: `MaxEncodedLen`)
	fn create_new_region() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `442`
		//  Estimated: `3536`
		// Minimum execution time: 26_138_000 picoseconds.
		Weight::from_parts(28_653_000, 0)
			.saturating_add(Weight::from_parts(0, 3536))
			.saturating_add(T::DbWeight::get().reads(2))
			.saturating_add(T::DbWeight::get().writes(3))
	}
	/// Storage: `EducationRegions::RegionDetails` (r:1 w:0)
	/// Proof: `EducationRegions::RegionDetails` (`max_values`: None, `max_size`: Some(71), added: 2546, mode: `MaxEncodedLen`)
	/// Storage: `EducationRegions::RegionOwnerProposalId` (r:1 w:1)
	/// Proof: `EducationRegions::RegionOwnerProposalId` (`max_values`: None, `max_size`: Some(26), added: 2501, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `Balances::Holds` (r:1 w:1)
	/// Proof: `Balances::Holds` (`max_values`: None, `max_size`: Some(499), added: 2974, mode: `MaxEncodedLen`)
	/// Storage: `EducationRegions::ProposalCounter` (r:1 w:1)
	/// Proof: `EducationRegions::ProposalCounter` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `EducationRegions::RegionOwnerRoundsExpiring` (r:1 w:1)
	/// Proof: `EducationRegions::RegionOwnerRoundsExpiring` (`max_values`: None, `max_size`: Some(222), added: 2697, mode: `MaxEncodedLen`)
	/// Storage: `EducationRegions::RegionOwnerProposals` (r:0 w:1)
	/// Proof: `EducationRegions::RegionOwnerProposals` (`max_values`: None, `max_size`: Some(76), added: 2551, mode: `MaxEncodedLen`)
	/// Storage: `EducationRegions::OngoingRegionOwnerProposalVotes` (r:0 w:1)
	/// Proof: `EducationRegions::OngoingRegionOwnerProposalVotes` (`max_values`: None, `max_size`: Some(72), added: 2547, mode: `MaxEncodedLen`)
	fn propose_remove_regional_operator() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `566`
		//  Estimated: `3964`
		// Minimum execution time: 62_871_000 picoseconds.
		Weight::from_parts(64_413_000, 0)
			.saturating_add(Weight::from_parts(0, 3964))
			.saturating_add(T::DbWeight::get().reads(6))
			.saturating_add(T::DbWeight::get().writes(7))
	}
	/// Storage: `EducationRegions::RegionOwnerProposalId` (r:1 w:0)
	/// Proof: `EducationRegions::RegionOwnerProposalId` (`max_values`: None, `max_size`: Some(26), added: 2501, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `Balances::Holds` (r:1 w:1)
	/// Proof: `Balances::Holds` (`max_values`: None, `max_size`: Some(499), added: 2974, mode: `MaxEncodedLen`)
	/// Storage: `EducationRegions::OngoingRegionOwnerProposalVotes` (r:1 w:1)
	/// Proof: `EducationRegions::OngoingRegionOwnerProposalVotes` (`max_values`: None, `max_size`: Some(72), added: 2547, mode: `MaxEncodedLen`)
	/// Storage: `EducationRegions::UserRegionOwnerVote` (r:1 w:1)
	/// Proof: `EducationRegions::UserRegionOwnerVote` (`max_values`: None, `max_size`: Some(91), added: 2566, mode: `MaxEncodedLen`)
	fn vote_on_remove_owner_proposal() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `675`
		//  Estimated: `3964`
		// Minimum execution time: 85_445_000 picoseconds.
		Weight::from_parts(88_697_000, 0)
			.saturating_add(Weight::from_parts(0, 3964))
			.saturating_add(T::DbWeight::get().reads(5))
			.saturating_add(T::DbWeight::get().writes(4))
	}
	/// Storage: `EducationRegions::UserRegionOwnerVote` (r:1 w:1)
	/// Proof: `EducationRegions::UserRegionOwnerVote` (`max_values`: None, `max_size`: Some(91), added: 2566, mode: `MaxEncodedLen`)
	/// Storage: `EducationRegions::RegionOwnerProposals` (r:1 w:0)
	/// Proof: `EducationRegions::RegionOwnerProposals` (`max_values`: None, `max_size`: Some(76), added: 2551, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `Balances::Holds` (r:1 w:1)
	/// Proof: `Balances::Holds` (`max_values`: None, `max_size`: Some(499), added: 2974, mode: `MaxEncodedLen`)
	fn unlock_region_owner_removal_voting_token() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `597`
		//  Estimated: `3964`
		// Minimum execution time: 49_861_000 picoseconds.
		Weight::from_parts(53_059_000, 0)
			.saturating_add(Weight::from_parts(0, 3964))
			.saturating_add(T::DbWeight::get().reads(4))
			.saturating_add(T::DbWeight::get().writes(3))
	}
	/// Storage: `XcavateWhitelist::AccountRoles` (r:1 w:0)
	/// Proof: `XcavateWhitelist::AccountRoles` (`max_values`: None, `max_size`: Some(66), added: 2541, mode: `MaxEncodedLen`)
	/// Storage: `EducationRegions::RegionDetails` (r:1 w:0)
	/// Proof: `EducationRegions::RegionDetails` (`max_values`: None, `max_size`: Some(71), added: 2546, mode: `MaxEncodedLen`)
	/// Storage: `EducationRegions::RegionReplacementAuctions` (r:1 w:1)
	/// Proof: `EducationRegions::RegionReplacementAuctions` (`max_values`: None, `max_size`: Some(71), added: 2546, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:2 w:2)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `Balances::Holds` (r:2 w:2)
	/// Proof: `Balances::Holds` (`max_values`: None, `max_size`: Some(499), added: 2974, mode: `MaxEncodedLen`)
	fn bid_on_region_replacement() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `926`
		//  Estimated: `6938`
		// Minimum execution time: 94_847_000 picoseconds.
		Weight::from_parts(154_577_000, 0)
			.saturating_add(Weight::from_parts(0, 6938))
			.saturating_add(T::DbWeight::get().reads(7))
			.saturating_add(T::DbWeight::get().writes(5))
	}
	/// Storage: `XcavateWhitelist::AccountRoles` (r:1 w:0)
	/// Proof: `XcavateWhitelist::AccountRoles` (`max_values`: None, `max_size`: Some(66), added: 2541, mode: `MaxEncodedLen`)
	/// Storage: `EducationRegions::RegionDetails` (r:1 w:1)
	/// Proof: `EducationRegions::RegionDetails` (`max_values`: None, `max_size`: Some(71), added: 2546, mode: `MaxEncodedLen`)
	fn initiate_region_owner_resignation() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `409`
		//  Estimated: `3536`
		// Minimum execution time: 22_156_000 picoseconds.
		Weight::from_parts(22_953_000, 0)
			.saturating_add(Weight::from_parts(0, 3536))
			.saturating_add(T::DbWeight::get().reads(2))
			.saturating_add(T::DbWeight::get().writes(1))
	}
}
