
//! Autogenerated weights for `pallet_real_x_education`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 48.0.0
//! DATE: 2026-06-15, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `recrafter-Legion-5-16IRX9`, CPU: `Intel(R) Core(TM) i7-14650HX`
//! WASM-EXECUTION: `Compiled`, CHAIN: `None`, DB CACHE: 1024

// Executed Command:
// ./target/release/xcavate-node
// benchmark
// pallet
// --pallet
// pallet_real_x_education
// --extrinsic
// *
// --steps
// 50
// --repeat
// 20
// --output
// ./runtime/src/weights/pallet_real_x_education.rs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use frame_support::{traits::Get, weights::Weight};
use core::marker::PhantomData;

/// Weight functions for `pallet_real_x_education`.
pub struct WeightInfo<T>(PhantomData<T>);
impl<T: frame_system::Config> pallet_real_x_education::WeightInfo for WeightInfo<T> {
	/// Storage: `XcavateWhitelist::AccountRoles` (r:1 w:0)
	/// Proof: `XcavateWhitelist::AccountRoles` (`max_values`: None, `max_size`: Some(66), added: 2541, mode: `MaxEncodedLen`)
	/// Storage: `EducationRegions::RegionDetails` (r:1 w:0)
	/// Proof: `EducationRegions::RegionDetails` (`max_values`: None, `max_size`: Some(71), added: 2546, mode: `MaxEncodedLen`)
	/// Storage: `RealXEducation::NextModuleId` (r:1 w:1)
	/// Proof: `RealXEducation::NextModuleId` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:2 w:2)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `Balances::Holds` (r:1 w:1)
	/// Proof: `Balances::Holds` (`max_values`: None, `max_size`: Some(499), added: 2974, mode: `MaxEncodedLen`)
	/// Storage: `EducationNfts::NextCollectionId` (r:1 w:1)
	/// Proof: `EducationNfts::NextCollectionId` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `EducationNfts::Collection` (r:1 w:1)
	/// Proof: `EducationNfts::Collection` (`max_values`: None, `max_size`: Some(84), added: 2559, mode: `MaxEncodedLen`)
	/// Storage: `RealXEducation::NextNftId` (r:1 w:1)
	/// Proof: `RealXEducation::NextNftId` (`max_values`: None, `max_size`: Some(24), added: 2499, mode: `MaxEncodedLen`)
	/// Storage: `EducationNfts::Item` (r:1 w:1)
	/// Proof: `EducationNfts::Item` (`max_values`: None, `max_size`: Some(861), added: 3336, mode: `MaxEncodedLen`)
	/// Storage: `EducationNfts::ItemConfigOf` (r:1 w:1)
	/// Proof: `EducationNfts::ItemConfigOf` (`max_values`: None, `max_size`: Some(48), added: 2523, mode: `MaxEncodedLen`)
	/// Storage: `EducationNfts::ItemMetadataOf` (r:1 w:1)
	/// Proof: `EducationNfts::ItemMetadataOf` (`max_values`: None, `max_size`: Some(5091), added: 7566, mode: `MaxEncodedLen`)
	/// Storage: `RealXEducation::NextAssetId` (r:1 w:1)
	/// Proof: `RealXEducation::NextAssetId` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `EducationAssets::Asset` (r:1 w:1)
	/// Proof: `EducationAssets::Asset` (`max_values`: None, `max_size`: Some(210), added: 2685, mode: `MaxEncodedLen`)
	/// Storage: `EducationAssets::NextAssetId` (r:1 w:0)
	/// Proof: `EducationAssets::NextAssetId` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `EducationAssets::Account` (r:1 w:1)
	/// Proof: `EducationAssets::Account` (`max_values`: None, `max_size`: Some(134), added: 2609, mode: `MaxEncodedLen`)
	/// Storage: `EducationAssets::Metadata` (r:1 w:1)
	/// Proof: `EducationAssets::Metadata` (`max_values`: None, `max_size`: Some(10042), added: 12517, mode: `MaxEncodedLen`)
	/// Storage: `RealXEducation::ModuleInfo` (r:0 w:1)
	/// Proof: `RealXEducation::ModuleInfo` (`max_values`: None, `max_size`: Some(150), added: 2625, mode: `MaxEncodedLen`)
	/// Storage: `EducationNfts::CollectionRoleOf` (r:0 w:1)
	/// Proof: `EducationNfts::CollectionRoleOf` (`max_values`: None, `max_size`: Some(69), added: 2544, mode: `MaxEncodedLen`)
	/// Storage: `EducationNfts::CollectionConfigOf` (r:0 w:1)
	/// Proof: `EducationNfts::CollectionConfigOf` (`max_values`: None, `max_size`: Some(73), added: 2548, mode: `MaxEncodedLen`)
	/// Storage: `EducationNfts::Account` (r:0 w:1)
	/// Proof: `EducationNfts::Account` (`max_values`: None, `max_size`: Some(88), added: 2563, mode: `MaxEncodedLen`)
	/// Storage: `EducationNfts::CollectionAccount` (r:0 w:1)
	/// Proof: `EducationNfts::CollectionAccount` (`max_values`: None, `max_size`: Some(68), added: 2543, mode: `MaxEncodedLen`)
	fn create_module() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `900`
		//  Estimated: `13507`
		// Minimum execution time: 406_106_000 picoseconds.
		Weight::from_parts(414_252_000, 0)
			.saturating_add(Weight::from_parts(0, 13507))
			.saturating_add(T::DbWeight::get().reads(17))
			.saturating_add(T::DbWeight::get().writes(19))
	}
	/// Storage: `XcavateWhitelist::AccountRoles` (r:1 w:0)
	/// Proof: `XcavateWhitelist::AccountRoles` (`max_values`: None, `max_size`: Some(66), added: 2541, mode: `MaxEncodedLen`)
	/// Storage: `RealXEducation::ModuleInfo` (r:1 w:1)
	/// Proof: `RealXEducation::ModuleInfo` (`max_values`: None, `max_size`: Some(150), added: 2625, mode: `MaxEncodedLen`)
	/// Storage: `Assets::Metadata` (r:1 w:0)
	/// Proof: `Assets::Metadata` (`max_values`: None, `max_size`: Some(10042), added: 12517, mode: `MaxEncodedLen`)
	/// Storage: `Assets::Asset` (r:1 w:1)
	/// Proof: `Assets::Asset` (`max_values`: None, `max_size`: Some(210), added: 2685, mode: `MaxEncodedLen`)
	/// Storage: `Assets::Account` (r:1 w:1)
	/// Proof: `Assets::Account` (`max_values`: None, `max_size`: Some(134), added: 2609, mode: `MaxEncodedLen`)
	/// Storage: `AssetsHolder::BalancesOnHold` (r:1 w:1)
	/// Proof: `AssetsHolder::BalancesOnHold` (`max_values`: None, `max_size`: Some(84), added: 2559, mode: `MaxEncodedLen`)
	/// Storage: `AssetsHolder::Holds` (r:1 w:1)
	/// Proof: `AssetsHolder::Holds` (`max_values`: None, `max_size`: Some(103), added: 2578, mode: `MaxEncodedLen`)
	/// Storage: `EducationAssets::Asset` (r:1 w:1)
	/// Proof: `EducationAssets::Asset` (`max_values`: None, `max_size`: Some(210), added: 2685, mode: `MaxEncodedLen`)
	/// Storage: `EducationAssets::Account` (r:2 w:2)
	/// Proof: `EducationAssets::Account` (`max_values`: None, `max_size`: Some(134), added: 2609, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `RealXEducation::NextSponsorId` (r:1 w:1)
	/// Proof: `RealXEducation::NextSponsorId` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `RealXEducation::SponsoredModules` (r:0 w:1)
	/// Proof: `RealXEducation::SponsoredModules` (`max_values`: None, `max_size`: Some(88), added: 2563, mode: `MaxEncodedLen`)
	fn sponsor_module() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `2097`
		//  Estimated: `13507`
		// Minimum execution time: 224_461_000 picoseconds.
		Weight::from_parts(229_428_000, 0)
			.saturating_add(Weight::from_parts(0, 13507))
			.saturating_add(T::DbWeight::get().reads(12))
			.saturating_add(T::DbWeight::get().writes(11))
	}
	/// Storage: `XcavateWhitelist::AccountRoles` (r:1 w:0)
	/// Proof: `XcavateWhitelist::AccountRoles` (`max_values`: None, `max_size`: Some(66), added: 2541, mode: `MaxEncodedLen`)
	/// Storage: `RealXEducation::ModuleInfo` (r:1 w:1)
	/// Proof: `RealXEducation::ModuleInfo` (`max_values`: None, `max_size`: Some(150), added: 2625, mode: `MaxEncodedLen`)
	/// Storage: `RealXEducation::SponsoredModules` (r:1 w:1)
	/// Proof: `RealXEducation::SponsoredModules` (`max_values`: None, `max_size`: Some(88), added: 2563, mode: `MaxEncodedLen`)
	/// Storage: `RealXEducation::NextBookingId` (r:1 w:1)
	/// Proof: `RealXEducation::NextBookingId` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `Balances::Holds` (r:1 w:1)
	/// Proof: `Balances::Holds` (`max_values`: None, `max_size`: Some(499), added: 2974, mode: `MaxEncodedLen`)
	/// Storage: `EducationAssets::Asset` (r:1 w:1)
	/// Proof: `EducationAssets::Asset` (`max_values`: None, `max_size`: Some(210), added: 2685, mode: `MaxEncodedLen`)
	/// Storage: `EducationAssets::Account` (r:2 w:2)
	/// Proof: `EducationAssets::Account` (`max_values`: None, `max_size`: Some(134), added: 2609, mode: `MaxEncodedLen`)
	/// Storage: `RealXEducation::Bookings` (r:0 w:1)
	/// Proof: `RealXEducation::Bookings` (`max_values`: None, `max_size`: Some(5189), added: 7664, mode: `MaxEncodedLen`)
	fn book_module() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1445`
		//  Estimated: `6208`
		// Minimum execution time: 216_009_000 picoseconds.
		Weight::from_parts(220_573_000, 0)
			.saturating_add(Weight::from_parts(0, 6208))
			.saturating_add(T::DbWeight::get().reads(9))
			.saturating_add(T::DbWeight::get().writes(9))
	}
	/// Storage: `XcavateWhitelist::AccountRoles` (r:1 w:0)
	/// Proof: `XcavateWhitelist::AccountRoles` (`max_values`: None, `max_size`: Some(66), added: 2541, mode: `MaxEncodedLen`)
	/// Storage: `RealXEducation::Bookings` (r:1 w:1)
	/// Proof: `RealXEducation::Bookings` (`max_values`: None, `max_size`: Some(5189), added: 7664, mode: `MaxEncodedLen`)
	/// Storage: `RealXEducation::ModuleDeliverer` (r:1 w:1)
	/// Proof: `RealXEducation::ModuleDeliverer` (`max_values`: None, `max_size`: Some(73), added: 2548, mode: `MaxEncodedLen`)
	/// Storage: `RealXEducation::ModuleInfo` (r:1 w:1)
	/// Proof: `RealXEducation::ModuleInfo` (`max_values`: None, `max_size`: Some(150), added: 2625, mode: `MaxEncodedLen`)
	fn claim_booking() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `6016`
		//  Estimated: `8654`
		// Minimum execution time: 77_801_000 picoseconds.
		Weight::from_parts(81_503_000, 0)
			.saturating_add(Weight::from_parts(0, 8654))
			.saturating_add(T::DbWeight::get().reads(4))
			.saturating_add(T::DbWeight::get().writes(3))
	}
	/// Storage: `XcavateWhitelist::AccountRoles` (r:1 w:0)
	/// Proof: `XcavateWhitelist::AccountRoles` (`max_values`: None, `max_size`: Some(66), added: 2541, mode: `MaxEncodedLen`)
	/// Storage: `RealXEducation::Bookings` (r:1 w:1)
	/// Proof: `RealXEducation::Bookings` (`max_values`: None, `max_size`: Some(5189), added: 7664, mode: `MaxEncodedLen`)
	/// Storage: `RealXEducation::ModuleInfo` (r:1 w:0)
	/// Proof: `RealXEducation::ModuleInfo` (`max_values`: None, `max_size`: Some(150), added: 2625, mode: `MaxEncodedLen`)
	/// Storage: `EducationRegions::RegionDetails` (r:1 w:0)
	/// Proof: `EducationRegions::RegionDetails` (`max_values`: None, `max_size`: Some(71), added: 2546, mode: `MaxEncodedLen`)
	/// Storage: `RealXEducation::ModuleDeliverer` (r:1 w:1)
	/// Proof: `RealXEducation::ModuleDeliverer` (`max_values`: None, `max_size`: Some(73), added: 2548, mode: `MaxEncodedLen`)
	/// Storage: `EducationAssets::Asset` (r:1 w:1)
	/// Proof: `EducationAssets::Asset` (`max_values`: None, `max_size`: Some(210), added: 2685, mode: `MaxEncodedLen`)
	/// Storage: `EducationAssets::Account` (r:1 w:1)
	/// Proof: `EducationAssets::Account` (`max_values`: None, `max_size`: Some(134), added: 2609, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:5 w:5)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `Assets::Metadata` (r:1 w:0)
	/// Proof: `Assets::Metadata` (`max_values`: None, `max_size`: Some(10042), added: 12517, mode: `MaxEncodedLen`)
	/// Storage: `Assets::Asset` (r:1 w:1)
	/// Proof: `Assets::Asset` (`max_values`: None, `max_size`: Some(210), added: 2685, mode: `MaxEncodedLen`)
	/// Storage: `Assets::Account` (r:5 w:5)
	/// Proof: `Assets::Account` (`max_values`: None, `max_size`: Some(134), added: 2609, mode: `MaxEncodedLen`)
	/// Storage: `AssetsHolder::Holds` (r:1 w:1)
	/// Proof: `AssetsHolder::Holds` (`max_values`: None, `max_size`: Some(103), added: 2578, mode: `MaxEncodedLen`)
	/// Storage: `AssetsHolder::BalancesOnHold` (r:1 w:1)
	/// Proof: `AssetsHolder::BalancesOnHold` (`max_values`: None, `max_size`: Some(84), added: 2559, mode: `MaxEncodedLen`)
	/// Storage: `RealXEducation::NextNftId` (r:1 w:1)
	/// Proof: `RealXEducation::NextNftId` (`max_values`: None, `max_size`: Some(24), added: 2499, mode: `MaxEncodedLen`)
	/// Storage: `EducationNfts::Item` (r:3 w:3)
	/// Proof: `EducationNfts::Item` (`max_values`: None, `max_size`: Some(861), added: 3336, mode: `MaxEncodedLen`)
	/// Storage: `EducationNfts::Collection` (r:1 w:1)
	/// Proof: `EducationNfts::Collection` (`max_values`: None, `max_size`: Some(84), added: 2559, mode: `MaxEncodedLen`)
	/// Storage: `EducationNfts::CollectionConfigOf` (r:1 w:0)
	/// Proof: `EducationNfts::CollectionConfigOf` (`max_values`: None, `max_size`: Some(73), added: 2548, mode: `MaxEncodedLen`)
	/// Storage: `EducationNfts::ItemConfigOf` (r:3 w:3)
	/// Proof: `EducationNfts::ItemConfigOf` (`max_values`: None, `max_size`: Some(48), added: 2523, mode: `MaxEncodedLen`)
	/// Storage: `EducationNfts::CollectionRoleOf` (r:1 w:0)
	/// Proof: `EducationNfts::CollectionRoleOf` (`max_values`: None, `max_size`: Some(69), added: 2544, mode: `MaxEncodedLen`)
	/// Storage: `EducationNfts::ItemMetadataOf` (r:3 w:3)
	/// Proof: `EducationNfts::ItemMetadataOf` (`max_values`: None, `max_size`: Some(5091), added: 7566, mode: `MaxEncodedLen`)
	/// Storage: `EducationNfts::Account` (r:0 w:3)
	/// Proof: `EducationNfts::Account` (`max_values`: None, `max_size`: Some(88), added: 2563, mode: `MaxEncodedLen`)
	fn submit_impact_score() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `9269`
		//  Estimated: `23688`
		// Minimum execution time: 709_608_000 picoseconds.
		Weight::from_parts(719_114_000, 0)
			.saturating_add(Weight::from_parts(0, 23688))
			.saturating_add(T::DbWeight::get().reads(34))
			.saturating_add(T::DbWeight::get().writes(31))
	}
	/// Storage: `XcavateWhitelist::AccountRoles` (r:1 w:0)
	/// Proof: `XcavateWhitelist::AccountRoles` (`max_values`: None, `max_size`: Some(66), added: 2541, mode: `MaxEncodedLen`)
	/// Storage: `RealXEducation::Bookings` (r:1 w:0)
	/// Proof: `RealXEducation::Bookings` (`max_values`: None, `max_size`: Some(5189), added: 7664, mode: `MaxEncodedLen`)
	/// Storage: `RealXEducation::ModuleInfo` (r:1 w:0)
	/// Proof: `RealXEducation::ModuleInfo` (`max_values`: None, `max_size`: Some(150), added: 2625, mode: `MaxEncodedLen`)
	/// Storage: `RealXEducation::NextNftId` (r:1 w:1)
	/// Proof: `RealXEducation::NextNftId` (`max_values`: None, `max_size`: Some(24), added: 2499, mode: `MaxEncodedLen`)
	/// Storage: `EducationNfts::Item` (r:1 w:1)
	/// Proof: `EducationNfts::Item` (`max_values`: None, `max_size`: Some(861), added: 3336, mode: `MaxEncodedLen`)
	/// Storage: `EducationNfts::Collection` (r:1 w:1)
	/// Proof: `EducationNfts::Collection` (`max_values`: None, `max_size`: Some(84), added: 2559, mode: `MaxEncodedLen`)
	/// Storage: `EducationNfts::CollectionConfigOf` (r:1 w:0)
	/// Proof: `EducationNfts::CollectionConfigOf` (`max_values`: None, `max_size`: Some(73), added: 2548, mode: `MaxEncodedLen`)
	/// Storage: `EducationNfts::ItemConfigOf` (r:1 w:1)
	/// Proof: `EducationNfts::ItemConfigOf` (`max_values`: None, `max_size`: Some(48), added: 2523, mode: `MaxEncodedLen`)
	/// Storage: `EducationNfts::CollectionRoleOf` (r:1 w:0)
	/// Proof: `EducationNfts::CollectionRoleOf` (`max_values`: None, `max_size`: Some(69), added: 2544, mode: `MaxEncodedLen`)
	/// Storage: `EducationNfts::ItemMetadataOf` (r:1 w:1)
	/// Proof: `EducationNfts::ItemMetadataOf` (`max_values`: None, `max_size`: Some(5091), added: 7566, mode: `MaxEncodedLen`)
	/// Storage: `EducationNfts::Account` (r:0 w:1)
	/// Proof: `EducationNfts::Account` (`max_values`: None, `max_size`: Some(88), added: 2563, mode: `MaxEncodedLen`)
	fn mint_recipient_nft() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `7013`
		//  Estimated: `8654`
		// Minimum execution time: 165_741_000 picoseconds.
		Weight::from_parts(176_899_000, 0)
			.saturating_add(Weight::from_parts(0, 8654))
			.saturating_add(T::DbWeight::get().reads(10))
			.saturating_add(T::DbWeight::get().writes(6))
	}
	/// Storage: `XcavateWhitelist::AccountRoles` (r:1 w:0)
	/// Proof: `XcavateWhitelist::AccountRoles` (`max_values`: None, `max_size`: Some(66), added: 2541, mode: `MaxEncodedLen`)
	/// Storage: `RealXEducation::Bookings` (r:1 w:1)
	/// Proof: `RealXEducation::Bookings` (`max_values`: None, `max_size`: Some(5189), added: 7664, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `Balances::Holds` (r:1 w:1)
	/// Proof: `Balances::Holds` (`max_values`: None, `max_size`: Some(499), added: 2974, mode: `MaxEncodedLen`)
	fn finish_booking_process() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `6117`
		//  Estimated: `8654`
		// Minimum execution time: 114_413_000 picoseconds.
		Weight::from_parts(122_281_000, 0)
			.saturating_add(Weight::from_parts(0, 8654))
			.saturating_add(T::DbWeight::get().reads(4))
			.saturating_add(T::DbWeight::get().writes(3))
	}
	/// Storage: `XcavateWhitelist::AccountRoles` (r:1 w:0)
	/// Proof: `XcavateWhitelist::AccountRoles` (`max_values`: None, `max_size`: Some(66), added: 2541, mode: `MaxEncodedLen`)
	/// Storage: `RealXEducation::ModuleInfo` (r:1 w:1)
	/// Proof: `RealXEducation::ModuleInfo` (`max_values`: None, `max_size`: Some(150), added: 2625, mode: `MaxEncodedLen`)
	/// Storage: `EducationAssets::Account` (r:1 w:1)
	/// Proof: `EducationAssets::Account` (`max_values`: None, `max_size`: Some(134), added: 2609, mode: `MaxEncodedLen`)
	/// Storage: `EducationAssets::Asset` (r:1 w:1)
	/// Proof: `EducationAssets::Asset` (`max_values`: None, `max_size`: Some(210), added: 2685, mode: `MaxEncodedLen`)
	fn burn_unsponsored_token() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1040`
		//  Estimated: `3675`
		// Minimum execution time: 100_195_000 picoseconds.
		Weight::from_parts(104_498_000, 0)
			.saturating_add(Weight::from_parts(0, 3675))
			.saturating_add(T::DbWeight::get().reads(4))
			.saturating_add(T::DbWeight::get().writes(3))
	}
	/// Storage: `XcavateWhitelist::AccountRoles` (r:1 w:0)
	/// Proof: `XcavateWhitelist::AccountRoles` (`max_values`: None, `max_size`: Some(66), added: 2541, mode: `MaxEncodedLen`)
	/// Storage: `RealXEducation::ModuleInfo` (r:1 w:1)
	/// Proof: `RealXEducation::ModuleInfo` (`max_values`: None, `max_size`: Some(150), added: 2625, mode: `MaxEncodedLen`)
	/// Storage: `EducationAssets::Asset` (r:1 w:1)
	/// Proof: `EducationAssets::Asset` (`max_values`: None, `max_size`: Some(210), added: 2685, mode: `MaxEncodedLen`)
	/// Storage: `EducationAssets::Metadata` (r:1 w:1)
	/// Proof: `EducationAssets::Metadata` (`max_values`: None, `max_size`: Some(10042), added: 12517, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:2 w:2)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `Balances::Holds` (r:1 w:1)
	/// Proof: `Balances::Holds` (`max_values`: None, `max_size`: Some(499), added: 2974, mode: `MaxEncodedLen`)
	fn remove_module() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1305`
		//  Estimated: `13507`
		// Minimum execution time: 153_613_000 picoseconds.
		Weight::from_parts(157_083_000, 0)
			.saturating_add(Weight::from_parts(0, 13507))
			.saturating_add(T::DbWeight::get().reads(7))
			.saturating_add(T::DbWeight::get().writes(6))
	}
	/// Storage: `XcavateWhitelist::AccountRoles` (r:1 w:0)
	/// Proof: `XcavateWhitelist::AccountRoles` (`max_values`: None, `max_size`: Some(66), added: 2541, mode: `MaxEncodedLen`)
	/// Storage: `RealXEducation::ModuleInfo` (r:1 w:1)
	/// Proof: `RealXEducation::ModuleInfo` (`max_values`: None, `max_size`: Some(150), added: 2625, mode: `MaxEncodedLen`)
	/// Storage: `RealXEducation::SponsoredModules` (r:1 w:1)
	/// Proof: `RealXEducation::SponsoredModules` (`max_values`: None, `max_size`: Some(88), added: 2563, mode: `MaxEncodedLen`)
	/// Storage: `Assets::Metadata` (r:1 w:0)
	/// Proof: `Assets::Metadata` (`max_values`: None, `max_size`: Some(10042), added: 12517, mode: `MaxEncodedLen`)
	/// Storage: `Assets::Asset` (r:1 w:1)
	/// Proof: `Assets::Asset` (`max_values`: None, `max_size`: Some(210), added: 2685, mode: `MaxEncodedLen`)
	/// Storage: `Assets::Account` (r:1 w:1)
	/// Proof: `Assets::Account` (`max_values`: None, `max_size`: Some(134), added: 2609, mode: `MaxEncodedLen`)
	/// Storage: `AssetsHolder::Holds` (r:1 w:1)
	/// Proof: `AssetsHolder::Holds` (`max_values`: None, `max_size`: Some(103), added: 2578, mode: `MaxEncodedLen`)
	/// Storage: `AssetsHolder::BalancesOnHold` (r:1 w:1)
	/// Proof: `AssetsHolder::BalancesOnHold` (`max_values`: None, `max_size`: Some(84), added: 2559, mode: `MaxEncodedLen`)
	/// Storage: `EducationAssets::Asset` (r:1 w:1)
	/// Proof: `EducationAssets::Asset` (`max_values`: None, `max_size`: Some(210), added: 2685, mode: `MaxEncodedLen`)
	/// Storage: `EducationAssets::Account` (r:2 w:2)
	/// Proof: `EducationAssets::Account` (`max_values`: None, `max_size`: Some(134), added: 2609, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	fn reclaim_unused_sponsorship() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `2533`
		//  Estimated: `13507`
		// Minimum execution time: 224_648_000 picoseconds.
		Weight::from_parts(231_079_000, 0)
			.saturating_add(Weight::from_parts(0, 13507))
			.saturating_add(T::DbWeight::get().reads(12))
			.saturating_add(T::DbWeight::get().writes(10))
	}
	/// Storage: `XcavateWhitelist::AccountRoles` (r:1 w:0)
	/// Proof: `XcavateWhitelist::AccountRoles` (`max_values`: None, `max_size`: Some(66), added: 2541, mode: `MaxEncodedLen`)
	/// Storage: `RealXEducation::ModuleInfo` (r:1 w:1)
	/// Proof: `RealXEducation::ModuleInfo` (`max_values`: None, `max_size`: Some(150), added: 2625, mode: `MaxEncodedLen`)
	/// Storage: `RealXEducation::Bookings` (r:1 w:1)
	/// Proof: `RealXEducation::Bookings` (`max_values`: None, `max_size`: Some(5189), added: 7664, mode: `MaxEncodedLen`)
	/// Storage: `RealXEducation::BookingCancellationCounter` (r:1 w:1)
	/// Proof: `RealXEducation::BookingCancellationCounter` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `EducationAssets::Asset` (r:1 w:1)
	/// Proof: `EducationAssets::Asset` (`max_values`: None, `max_size`: Some(210), added: 2685, mode: `MaxEncodedLen`)
	/// Storage: `EducationAssets::Account` (r:2 w:2)
	/// Proof: `EducationAssets::Account` (`max_values`: None, `max_size`: Some(134), added: 2609, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `Balances::Holds` (r:1 w:1)
	/// Proof: `Balances::Holds` (`max_values`: None, `max_size`: Some(499), added: 2974, mode: `MaxEncodedLen`)
	/// Storage: `RealXEducation::SponsoredModules` (r:1 w:1)
	/// Proof: `RealXEducation::SponsoredModules` (`max_values`: None, `max_size`: Some(88), added: 2563, mode: `MaxEncodedLen`)
	/// Storage: `RealXEducation::ModuleDeliverer` (r:1 w:1)
	/// Proof: `RealXEducation::ModuleDeliverer` (`max_values`: None, `max_size`: Some(73), added: 2548, mode: `MaxEncodedLen`)
	/// Storage: `RealXEducation::SchoolCancellations` (r:0 w:1)
	/// Proof: `RealXEducation::SchoolCancellations` (`max_values`: None, `max_size`: Some(80), added: 2555, mode: `MaxEncodedLen`)
	fn cancel_booking() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `6990`
		//  Estimated: `8654`
		// Minimum execution time: 227_652_000 picoseconds.
		Weight::from_parts(236_656_000, 0)
			.saturating_add(Weight::from_parts(0, 8654))
			.saturating_add(T::DbWeight::get().reads(11))
			.saturating_add(T::DbWeight::get().writes(11))
	}
	/// Storage: `XcavateWhitelist::AccountRoles` (r:1 w:0)
	/// Proof: `XcavateWhitelist::AccountRoles` (`max_values`: None, `max_size`: Some(66), added: 2541, mode: `MaxEncodedLen`)
	/// Storage: `RealXEducation::SchoolCancellations` (r:51 w:50)
	/// Proof: `RealXEducation::SchoolCancellations` (`max_values`: None, `max_size`: Some(80), added: 2555, mode: `MaxEncodedLen`)
	/// Storage: `RealXEducation::BookingCancellationCounter` (r:1 w:1)
	/// Proof: `RealXEducation::BookingCancellationCounter` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	fn clear_old_cancellations() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `2620`
		//  Estimated: `131295`
		// Minimum execution time: 526_798_000 picoseconds.
		Weight::from_parts(538_202_000, 0)
			.saturating_add(Weight::from_parts(0, 131295))
			.saturating_add(T::DbWeight::get().reads(53))
			.saturating_add(T::DbWeight::get().writes(51))
	}
	/// Storage: `XcavateWhitelist::AccountRoles` (r:1 w:0)
	/// Proof: `XcavateWhitelist::AccountRoles` (`max_values`: None, `max_size`: Some(66), added: 2541, mode: `MaxEncodedLen`)
	/// Storage: `RealXEducation::ModuleInfo` (r:1 w:1)
	/// Proof: `RealXEducation::ModuleInfo` (`max_values`: None, `max_size`: Some(150), added: 2625, mode: `MaxEncodedLen`)
	/// Storage: `RealXEducation::Bookings` (r:1 w:1)
	/// Proof: `RealXEducation::Bookings` (`max_values`: None, `max_size`: Some(5189), added: 7664, mode: `MaxEncodedLen`)
	/// Storage: `RealXEducation::ModuleDeliverer` (r:1 w:1)
	/// Proof: `RealXEducation::ModuleDeliverer` (`max_values`: None, `max_size`: Some(73), added: 2548, mode: `MaxEncodedLen`)
	fn cancel_claim() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `6052`
		//  Estimated: `8654`
		// Minimum execution time: 75_359_000 picoseconds.
		Weight::from_parts(79_537_000, 0)
			.saturating_add(Weight::from_parts(0, 8654))
			.saturating_add(T::DbWeight::get().reads(4))
			.saturating_add(T::DbWeight::get().writes(3))
	}
	/// Storage: `XcavateWhitelist::AccountRoles` (r:1 w:0)
	/// Proof: `XcavateWhitelist::AccountRoles` (`max_values`: None, `max_size`: Some(66), added: 2541, mode: `MaxEncodedLen`)
	/// Storage: `RealXEducation::ModuleDeliverer` (r:1 w:1)
	/// Proof: `RealXEducation::ModuleDeliverer` (`max_values`: None, `max_size`: Some(73), added: 2548, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `Balances::Holds` (r:1 w:1)
	/// Proof: `Balances::Holds` (`max_values`: None, `max_size`: Some(499), added: 2974, mode: `MaxEncodedLen`)
	fn register_module_deliverer() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `425`
		//  Estimated: `3964`
		// Minimum execution time: 95_166_000 picoseconds.
		Weight::from_parts(97_694_000, 0)
			.saturating_add(Weight::from_parts(0, 3964))
			.saturating_add(T::DbWeight::get().reads(4))
			.saturating_add(T::DbWeight::get().writes(3))
	}
	/// Storage: `XcavateWhitelist::AccountRoles` (r:1 w:1)
	/// Proof: `XcavateWhitelist::AccountRoles` (`max_values`: None, `max_size`: Some(66), added: 2541, mode: `MaxEncodedLen`)
	/// Storage: `RealXEducation::ModuleDeliverer` (r:1 w:1)
	/// Proof: `RealXEducation::ModuleDeliverer` (`max_values`: None, `max_size`: Some(73), added: 2548, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `Balances::Holds` (r:1 w:1)
	/// Proof: `Balances::Holds` (`max_values`: None, `max_size`: Some(499), added: 2974, mode: `MaxEncodedLen`)
	fn unregister_module_deliverer() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `579`
		//  Estimated: `3964`
		// Minimum execution time: 96_527_000 picoseconds.
		Weight::from_parts(100_460_000, 0)
			.saturating_add(Weight::from_parts(0, 3964))
			.saturating_add(T::DbWeight::get().reads(4))
			.saturating_add(T::DbWeight::get().writes(4))
	}
}
