
//! Autogenerated weights for `pallet_token_gateway`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 51.0.0
//! DATE: 2025-11-10, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `tux`, CPU: `12th Gen Intel(R) Core(TM) i7-12700H`
//! WASM-EXECUTION: `Compiled`, CHAIN: `None`, DB CACHE: 1024

// Executed Command:
//  pop
//  bench
//  pallet
//  --runtime=./target/release/wbuild/xcavate-runtime/xcavate_runtime.compact.compressed.wasm
//  --pallets=ismp_parachain,pallet_token_gateway
//  --extrinsic=
//  --steps=50
//  --output=./runtime/src/weights/
//  --genesis-builder=none

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use frame_support::{traits::Get, weights::Weight};
use core::marker::PhantomData;

/// Weight functions for `pallet_token_gateway`.
pub struct WeightInfo<T>(PhantomData<T>);
impl<T: frame_system::Config> pallet_token_gateway::WeightInfo for WeightInfo<T> {
	/// Storage: `Hyperbridge::HostParams` (r:1 w:0)
	/// Proof: `Hyperbridge::HostParams` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `Ismp::Nonce` (r:1 w:1)
	/// Proof: `Ismp::Nonce` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `TokenGateway::Precisions` (r:0 w:100)
	/// Proof: `TokenGateway::Precisions` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `TokenGateway::NativeAssets` (r:0 w:1)
	/// Proof: `TokenGateway::NativeAssets` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `TokenGateway::LocalAssets` (r:0 w:1)
	/// Proof: `TokenGateway::LocalAssets` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `TokenGateway::SupportedAssets` (r:0 w:1)
	/// Proof: `TokenGateway::SupportedAssets` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e74732115797c00c0f40e41a0d7c1f56a` (r:1 w:1)
	/// Proof: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e74732115797c00c0f40e41a0d7c1f56a` (r:1 w:1)
	/// Storage: UNKNOWN KEY `0x526571756573745061796d656e742115797c00c0f40e41a0d7c1f56a2821b06f` (r:0 w:1)
	/// Proof: UNKNOWN KEY `0x526571756573745061796d656e742115797c00c0f40e41a0d7c1f56a2821b06f` (r:0 w:1)
	/// The range of component `x` is `[1, 100]`.
	fn create_erc6160_asset(x: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `3465`
		// Minimum execution time: 28_223_000 picoseconds.
		Weight::from_parts(27_786_739, 0)
			.saturating_add(Weight::from_parts(0, 3465))
			// Standard Error: 2_231
			.saturating_add(Weight::from_parts(2_217_567, 0).saturating_mul(x.into()))
			.saturating_add(T::DbWeight::get().reads(3))
			.saturating_add(T::DbWeight::get().writes(6))
			.saturating_add(T::DbWeight::get().writes((1_u64).saturating_mul(x.into())))
	}
	/// Storage: `TokenGateway::SupportedAssets` (r:1 w:0)
	/// Proof: `TokenGateway::SupportedAssets` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `TokenGateway::NativeAssets` (r:1 w:0)
	/// Proof: `TokenGateway::NativeAssets` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `TokenGateway::Precisions` (r:1 w:0)
	/// Proof: `TokenGateway::Precisions` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Hyperbridge::HostParams` (r:1 w:0)
	/// Proof: `Hyperbridge::HostParams` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `Ismp::Nonce` (r:1 w:1)
	/// Proof: `Ismp::Nonce` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e74732a0bd054c957b2af9cbd84b26f0b` (r:1 w:1)
	/// Proof: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e74732a0bd054c957b2af9cbd84b26f0b` (r:1 w:1)
	/// Storage: UNKNOWN KEY `0x526571756573745061796d656e742a0bd054c957b2af9cbd84b26f0b3d81d11c` (r:0 w:1)
	/// Proof: UNKNOWN KEY `0x526571756573745061796d656e742a0bd054c957b2af9cbd84b26f0b3d81d11c` (r:0 w:1)
	fn teleport() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `335`
		//  Estimated: `3800`
		// Minimum execution time: 86_065_000 picoseconds.
		Weight::from_parts(88_042_000, 0)
			.saturating_add(Weight::from_parts(0, 3800))
			.saturating_add(T::DbWeight::get().reads(7))
			.saturating_add(T::DbWeight::get().writes(4))
	}
	/// Storage: `TokenGateway::TokenGatewayAddresses` (r:0 w:1)
	/// Proof: `TokenGateway::TokenGatewayAddresses` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// The range of component `x` is `[1, 100]`.
	fn set_token_gateway_addresses(_x: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 3_833_000 picoseconds.
		Weight::from_parts(4_206_921, 0)
			.saturating_add(Weight::from_parts(0, 0))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `Hyperbridge::HostParams` (r:1 w:0)
	/// Proof: `Hyperbridge::HostParams` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `Ismp::Nonce` (r:1 w:1)
	/// Proof: `Ismp::Nonce` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e747371ff6b41da2e76106635a3f9eba1` (r:1 w:1)
	/// Proof: UNKNOWN KEY `0x52657175657374436f6d6d69746d656e747371ff6b41da2e76106635a3f9eba1` (r:1 w:1)
	/// Storage: UNKNOWN KEY `0x526571756573745061796d656e7471ff6b41da2e76106635a3f9eba1c5fced6d` (r:0 w:1)
	/// Proof: UNKNOWN KEY `0x526571756573745061796d656e7471ff6b41da2e76106635a3f9eba1c5fced6d` (r:0 w:1)
	fn update_erc6160_asset() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `135`
		//  Estimated: `3600`
		// Minimum execution time: 26_105_000 picoseconds.
		Weight::from_parts(27_255_000, 0)
			.saturating_add(Weight::from_parts(0, 3600))
			.saturating_add(T::DbWeight::get().reads(3))
			.saturating_add(T::DbWeight::get().writes(3))
	}
	/// Storage: `TokenGateway::Precisions` (r:0 w:100)
	/// Proof: `TokenGateway::Precisions` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// The range of component `x` is `[1, 100]`.
	fn update_asset_precision(x: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 4_022_000 picoseconds.
		Weight::from_parts(1_134_405, 0)
			.saturating_add(Weight::from_parts(0, 0))
			// Standard Error: 2_607
			.saturating_add(Weight::from_parts(2_152_132, 0).saturating_mul(x.into()))
			.saturating_add(T::DbWeight::get().writes((1_u64).saturating_mul(x.into())))
	}
}
