
//! Autogenerated weights for `public_credentials`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 48.0.0
//! DATE: 2026-02-13, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `recrafter-Legion-5-16IRX9`, CPU: `Intel(R) Core(TM) i7-14650HX`
//! WASM-EXECUTION: `Compiled`, CHAIN: `None`, DB CACHE: 1024

// Executed Command:
// ./target/release/xcavate-node
// benchmark
// pallet
// --pallet
// public_credentials
// --extrinsic
// *
// --steps
// 50
// --repeat
// 20
// --output
// ./runtime/src/weights/public_credentials.rs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use frame_support::{traits::Get, weights::Weight};
use core::marker::PhantomData;

/// Weight functions for `public_credentials`.
pub struct WeightInfo<T>(PhantomData<T>);
impl<T: frame_system::Config> public_credentials::WeightInfo for WeightInfo<T> {
	/// Storage: `Ctype::Ctypes` (r:1 w:0)
	/// Proof: `Ctype::Ctypes` (`max_values`: None, `max_size`: Some(84), added: 2559, mode: `MaxEncodedLen`)
	/// Storage: `PublicCredentials::Credentials` (r:1 w:1)
	/// Proof: `PublicCredentials::Credentials` (`max_values`: None, `max_size`: Some(471), added: 2946, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `Balances::Holds` (r:1 w:1)
	/// Proof: `Balances::Holds` (`max_values`: None, `max_size`: Some(463), added: 2938, mode: `MaxEncodedLen`)
	/// Storage: `PublicCredentials::CredentialSubjects` (r:0 w:1)
	/// Proof: `PublicCredentials::CredentialSubjects` (`max_values`: None, `max_size`: Some(312), added: 2787, mode: `MaxEncodedLen`)
	/// Storage: `KiltMigration::MigratedKeys` (r:0 w:1)
	/// Proof: `KiltMigration::MigratedKeys` (`max_values`: None, `max_size`: Some(48), added: 2523, mode: `MaxEncodedLen`)
	/// The range of component `c` is `[1, 100000]`.
	fn add(c: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `326`
		//  Estimated: `3936`
		// Minimum execution time: 108_503_000 picoseconds.
		Weight::from_parts(103_303_710, 0)
			.saturating_add(Weight::from_parts(0, 3936))
			// Standard Error: 10
			.saturating_add(Weight::from_parts(3_523, 0).saturating_mul(c.into()))
			.saturating_add(T::DbWeight::get().reads(4))
			.saturating_add(T::DbWeight::get().writes(5))
	}
	/// Storage: `PublicCredentials::CredentialSubjects` (r:1 w:0)
	/// Proof: `PublicCredentials::CredentialSubjects` (`max_values`: None, `max_size`: Some(312), added: 2787, mode: `MaxEncodedLen`)
	/// Storage: `PublicCredentials::Credentials` (r:1 w:1)
	/// Proof: `PublicCredentials::Credentials` (`max_values`: None, `max_size`: Some(471), added: 2946, mode: `MaxEncodedLen`)
	fn revoke() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `882`
		//  Estimated: `3936`
		// Minimum execution time: 34_994_000 picoseconds.
		Weight::from_parts(36_084_000, 0)
			.saturating_add(Weight::from_parts(0, 3936))
			.saturating_add(T::DbWeight::get().reads(2))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `PublicCredentials::CredentialSubjects` (r:1 w:0)
	/// Proof: `PublicCredentials::CredentialSubjects` (`max_values`: None, `max_size`: Some(312), added: 2787, mode: `MaxEncodedLen`)
	/// Storage: `PublicCredentials::Credentials` (r:1 w:1)
	/// Proof: `PublicCredentials::Credentials` (`max_values`: None, `max_size`: Some(471), added: 2946, mode: `MaxEncodedLen`)
	fn unrevoke() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `882`
		//  Estimated: `3936`
		// Minimum execution time: 34_991_000 picoseconds.
		Weight::from_parts(36_050_000, 0)
			.saturating_add(Weight::from_parts(0, 3936))
			.saturating_add(T::DbWeight::get().reads(2))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `PublicCredentials::CredentialSubjects` (r:1 w:1)
	/// Proof: `PublicCredentials::CredentialSubjects` (`max_values`: None, `max_size`: Some(312), added: 2787, mode: `MaxEncodedLen`)
	/// Storage: `PublicCredentials::Credentials` (r:1 w:1)
	/// Proof: `PublicCredentials::Credentials` (`max_values`: None, `max_size`: Some(471), added: 2946, mode: `MaxEncodedLen`)
	/// Storage: `KiltMigration::MigratedKeys` (r:1 w:0)
	/// Proof: `KiltMigration::MigratedKeys` (`max_values`: None, `max_size`: Some(48), added: 2523, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `Balances::Holds` (r:1 w:1)
	/// Proof: `Balances::Holds` (`max_values`: None, `max_size`: Some(463), added: 2938, mode: `MaxEncodedLen`)
	fn remove() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1155`
		//  Estimated: `3936`
		// Minimum execution time: 106_958_000 picoseconds.
		Weight::from_parts(110_013_000, 0)
			.saturating_add(Weight::from_parts(0, 3936))
			.saturating_add(T::DbWeight::get().reads(5))
			.saturating_add(T::DbWeight::get().writes(4))
	}
	/// Storage: `PublicCredentials::CredentialSubjects` (r:1 w:1)
	/// Proof: `PublicCredentials::CredentialSubjects` (`max_values`: None, `max_size`: Some(312), added: 2787, mode: `MaxEncodedLen`)
	/// Storage: `PublicCredentials::Credentials` (r:1 w:1)
	/// Proof: `PublicCredentials::Credentials` (`max_values`: None, `max_size`: Some(471), added: 2946, mode: `MaxEncodedLen`)
	/// Storage: `KiltMigration::MigratedKeys` (r:1 w:0)
	/// Proof: `KiltMigration::MigratedKeys` (`max_values`: None, `max_size`: Some(48), added: 2523, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `Balances::Holds` (r:1 w:1)
	/// Proof: `Balances::Holds` (`max_values`: None, `max_size`: Some(463), added: 2938, mode: `MaxEncodedLen`)
	fn reclaim_deposit() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1155`
		//  Estimated: `3936`
		// Minimum execution time: 107_045_000 picoseconds.
		Weight::from_parts(111_339_000, 0)
			.saturating_add(Weight::from_parts(0, 3936))
			.saturating_add(T::DbWeight::get().reads(5))
			.saturating_add(T::DbWeight::get().writes(4))
	}
	/// Storage: `PublicCredentials::CredentialSubjects` (r:1 w:0)
	/// Proof: `PublicCredentials::CredentialSubjects` (`max_values`: None, `max_size`: Some(312), added: 2787, mode: `MaxEncodedLen`)
	/// Storage: `PublicCredentials::Credentials` (r:1 w:1)
	/// Proof: `PublicCredentials::Credentials` (`max_values`: None, `max_size`: Some(471), added: 2946, mode: `MaxEncodedLen`)
	/// Storage: `KiltMigration::MigratedKeys` (r:1 w:0)
	/// Proof: `KiltMigration::MigratedKeys` (`max_values`: None, `max_size`: Some(48), added: 2523, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:2 w:2)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `Balances::Holds` (r:2 w:2)
	/// Proof: `Balances::Holds` (`max_values`: None, `max_size`: Some(463), added: 2938, mode: `MaxEncodedLen`)
	fn change_deposit_owner() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1256`
		//  Estimated: `6866`
		// Minimum execution time: 179_709_000 picoseconds.
		Weight::from_parts(182_221_000, 0)
			.saturating_add(Weight::from_parts(0, 6866))
			.saturating_add(T::DbWeight::get().reads(7))
			.saturating_add(T::DbWeight::get().writes(5))
	}
	/// Storage: `PublicCredentials::CredentialSubjects` (r:1 w:0)
	/// Proof: `PublicCredentials::CredentialSubjects` (`max_values`: None, `max_size`: Some(312), added: 2787, mode: `MaxEncodedLen`)
	/// Storage: `PublicCredentials::Credentials` (r:1 w:1)
	/// Proof: `PublicCredentials::Credentials` (`max_values`: None, `max_size`: Some(471), added: 2946, mode: `MaxEncodedLen`)
	/// Storage: `KiltMigration::MigratedKeys` (r:1 w:1)
	/// Proof: `KiltMigration::MigratedKeys` (`max_values`: None, `max_size`: Some(48), added: 2523, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `Balances::Holds` (r:1 w:1)
	/// Proof: `Balances::Holds` (`max_values`: None, `max_size`: Some(463), added: 2938, mode: `MaxEncodedLen`)
	fn update_deposit() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1042`
		//  Estimated: `3936`
		// Minimum execution time: 143_008_000 picoseconds.
		Weight::from_parts(146_470_000, 0)
			.saturating_add(Weight::from_parts(0, 3936))
			.saturating_add(T::DbWeight::get().reads(5))
			.saturating_add(T::DbWeight::get().writes(4))
	}
}
